In [1]:
import pandas as pd
from IPython.display import display

# Set pandas display options to show all columns
pd.set_option('display.max_columns', None)  
pd.set_option('display.width', None)        
pd.set_option('display.max_rows', None)     

# load all datasets
az_cocci = pd.read_csv("../../data/processed/arizona_cm_combined_data.csv")
az_pop = pd.read_csv("../../data/processed/arizona_pop_est_1980-2023.csv")
az_met = pd.read_csv("../../data/processed/Arizona_Weather_Data_Daily_Updates_1994_to_2023.csv")
ca_cocci = pd.read_csv("../../data/processed/Cali_Monthly_Cases.csv")
ca_pop = pd.read_csv("../../data/processed/California_Population_2000-2023.csv")
ca_met = pd.read_csv("../../data/processed/California_Weather_Data_Daily_Updates_2001_to_2022.csv")
az_co = pd.read_csv("../../data/processed/arizona_CO_1993_2023.csv", low_memory=False)
az_no2 = pd.read_csv("../../data/processed/arizona_NO2_1993_2023.csv", low_memory=False)
az_oz = pd.read_csv("../../data/processed/arizona_Ozone_1993_2023.csv", low_memory=False)
az_pm2_5 = pd.read_csv("../../data/processed/arizona_PM2.5_1993_2023.csv", low_memory=False)
az_pm2_5_nonref = pd.read_csv("../../data/processed/arizona_PM2.5_nonref_1993_2023.csv", low_memory=False)
az_pm10 = pd.read_csv("../../data/processed/arizona_PM10_1993_2023.csv", low_memory=False)
az_so2 = pd.read_csv("../../data/processed/arizona_SO2_1993_2023.csv", low_memory=False)
az_tsp = pd.read_csv("../../data/processed/arizona_TSP_1993_2023.csv", low_memory=False)
ca_co = pd.read_csv("../../data/processed/california_CO_2000_2022.csv", low_memory=False)
ca_no2 = pd.read_csv("../../data/processed/california_NO2_2000_2022.csv", low_memory=False)
ca_oz = pd.read_csv("../../data/processed/california_Ozone_2000_2022.csv", low_memory=False)
ca_pm2_5 = pd.read_csv("../../data/processed/california_PM2.5_2000_2022.csv", low_memory=False)
ca_pm2_5_nonref = pd.read_csv("../../data/processed/california_PM2.5_nonref_2000_2022.csv", low_memory=False)
ca_pm10 = pd.read_csv("../../data/processed/california_PM10_2000_2022.csv", low_memory=False)
ca_so2 = pd.read_csv("../../data/processed/california_SO2_2000_2022.csv", low_memory=False)
ca_tsp = pd.read_csv("../../data/processed/california_TSP_2000_2022.csv", low_memory=False)
ca_az_air_pollutants = pd.read_csv("../../data/processed/air_pollutants_ca_and_az.csv", low_memory=False)
ca_air_pollutants = pd.read_csv("../../data/processed/air_pollutants_ca.csv", low_memory=False)
az_air_pollutants = pd.read_csv("../../data/processed/air_pollutants_az.csv", low_memory=False)

# helps to display all the info from the datasets 
def display_info(df, title):
    print(f"\n{title} Info")
    print("="*50 +"\n" + "="*50)
    display(df.info())
    print(f"\n{title} Head")
    print("="*50 +"\n" + "="*50)
    display(df.head())
    print(f"\n{title} Tail")
    print("="*50 +"\n" + "="*50)
    display(df.tail())

# list of dataframes and their titles
dfs = [az_cocci, az_pop, az_met, ca_cocci, ca_pop, ca_met, 
       az_co, az_no2, az_oz, az_pm2_5, az_pm2_5_nonref, az_pm10, az_so2, az_tsp,
       ca_co, ca_no2, ca_oz, ca_pm2_5, ca_pm2_5_nonref, ca_pm10, ca_so2, ca_tsp, 
       ca_az_air_pollutants, ca_air_pollutants, az_air_pollutants]

dfs_titles = ['Arizona Cocci Case Count', 
              'Arizona Population Estimates',
              'Arizona Weather Data',
              'California Cocci Case Count',
              'California Population Estimates',
              'California Weather Data',
              'Arizona CO Data 1993-2023',
              'Arizona NO2 Data 1993-2023',
              'Arizona Ozone Data 1993-2023',
              'Arizona PM2.5 Data 1993-2023',
              'Arizona PM2.5 Non-Reference Data 1993-2023',
              'Arizona PM10 Data 1993-2023',
              'Arizona SO2 Data 1993-2023',
              'Arizona TSP Data 1993-2023',
              'California CO Data 2000-2022',
              'California NO2 Data 2000-2022',
              'California Ozone Data 2000-2022',
              'California PM2.5 Data 2000-2022',
              'California PM2.5 Non-Reference Data 2000-2022',
              'California PM10 Data 2000-2022',
              'California SO2 Data 2000-2022',
              'California TSP Data 2000-2022',
              'California and Arizona Air Pollutants',
              'California Air Pollutants',
              'Arizona Air Pollutants']


# The display_info function you already have will work with these lists:
for df, title in zip(dfs, dfs_titles):
    display_info(df, title)

Arizona Cocci Case Count Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Month        360 non-null    int64
 1   Apache       324 non-null    float64
 2   Cochise      360 non-null    int64
 3   Coconino     360 non-null    int64
 4   Gila         360 non-null    int64
 5   Graham       360 non-null    int64
 6   Greenlee     288 non-null    float64
 7   La Paz       360 non-null    int64
 8   Maricopa     360 non-null    int64
 9   Mohave       360 non-null    int64
 10  Navajo       360 non-null    int64
 11  Pima         360 non-null    int64
 12  Pinal        360 non-null    int64
 13  Santa Cruz   336 non-null    float64
 14  Yavapai      360 non-null    int64
 15  Yuma         360 non-null    int64
 16  Total        360 non-null    int64
 17  Year         360 non-null    int64
 18  DateTimeISO  360 non-null    object
dtypes: float64(3), int64(15), object(1)
memory usage: 53.6+ KB

None

Arizona Cocci Case Count Head
==================================================
==================================================

,Month,Apache,Cochise,Coconino,Gila,Graham,Greenlee,La Paz,Maricopa,Mohave,Navajo,Pima,Pinal,Santa Cruz,Yavapai,Yuma,Total,Year,DateTimeISO
0,1,NaN,1,0,1,1,1.0,0,24,0,0,11,1,NaN,0,1,42,1994,1994-01-01T00:00:00.000000
1,2,NaN,0,0,0,0,0.0,0,15,2,0,14,1,NaN,1,0,36,1994,1994-02-01T00:00:00.000000
2,3,NaN,0,1,0,0,0.0,0,23,0,0,9,4,NaN,0,0,40,1994,1994-03-01T00:00:00.000000
3,4,NaN,0,1,0,0,0.0,1,38,0,0,4,5,NaN,0,1,50,1994,1994-04-01T00:00:00.000000
4,5,NaN,0,0,1,0,0.0,0,28,1,0,11,4,NaN,0,0,45,1994,1994-05-01T00:00:00.000000

Arizona Cocci Case Count Tail
==================================================
==================================================

,Month,Apache,Cochise,Coconino,Gila,Graham,Greenlee,La Paz,Maricopa,Mohave,Navajo,Pima,Pinal,Santa Cruz,Yavapai,Yuma,Total,Year,DateTimeISO
355,8,6.0,6,5,3,2,0.0,2,733,11,6,115,97,1.0,13,7,1007,2023,2023-08-01T00:00:00.000000
356,9,6.0,3,7,3,1,0.0,2,673,24,6,94,76,2.0,11,4,912,2023,2023-09-01T00:00:00.000000
357,10,3.0,3,7,7,3,1.0,3,845,10,8,110,109,0.0,12,4,1125,2023,2023-10-01T00:00:00.000000
358,11,4.0,5,10,6,3,0.0,3,990,12,11,141,134,3.0,20,7,1349,2023,2023-11-01T00:00:00.000000
359,12,4.0,7,11,4,2,0.0,3,1069,12,6,129,136,2.0,14,5,1404,2023,2023-12-01T00:00:00.000000

Arizona Population Estimates Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 45 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   County  15 non-null     object
 1   1980    15 non-null     float64
 2   1981    15 non-null     float64
 3   1982    15 non-null     float64
 4   1983    15 non-null     float64
 5   1984    15 non-null     float64
 6   1985    15 non-null     float64
 7   1986    15 non-null     float64
 8   1987    15 non-null     float64
 9   1988    15 non-null     float64
 10  1989    15 non-null     float64
 11  1990    15 non-null     float64
 12  1991    15 non-null     float64
 13  1992    15 non-null     float64
 14  1993    15 non-null     float64
 15  1994    15 non-null     float64
 16  1995    15 non-null     float64
 17  1996    15 non-null     float64
 18  1997    15 non-null     float64
 19  1998    15 non-null     float64
 20  1999    15 non-null     float64
 21  2000    15 non-null     float64
 22  2001    15 non-null     float64
 23  2002    15 non-null     float64
 24  2003    15 non-null     float64
 25  2004    15 non-null     float64
 26  2005    15 non-null     float64
 27  2006    15 non-null     float64
 28  2007    15 non-null     float64
 29  2008    15 non-null     float64
 30  2009    15 non-null     float64
 31  2010    15 non-null     float64
 32  2011    15 non-null     float64
 33  2012    15 non-null     float64
 34  2013    15 non-null     float64
 35  2014    15 non-null     float64
 36  2015    15 non-null     float64
 37  2016    15 non-null     float64
 38  2017    15 non-null     float64
 39  2018    15 non-null     float64
 40  2019    15 non-null     float64
 41  2020    15 non-null     float64
 42  2021    15 non-null     float64
 43  2022    15 non-null     float64
 44  2023    15 non-null     float64
dtypes: float64(44), object(1)
memory usage: 5.4+ KB

None

Arizona Population Estimates Head
==================================================
==================================================

,County,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Apache,51630.568111,52048.223447,55277.376464,55911.894979,50914.597595,54821.709770,58490.235818,60001.042729,63410.834433,61161.079373,61645.502949,62126.291255,63363.526824,63644.332578,64052.384007,65272.652442,65624.642499,66895.874996,67900.825480,68688.658726,69411.521266,69315.019509,69073.213399,69165.288496,69738.101335,71242.999494,71455.733916,71900.695845,72030.046687,72023.644810,71520.424271,71167.025319,70824.832178,70047.407442,69100.965530,68791.695569,68305.100270,67988.285524,67931.893866,65906.751345,66050.0,66411.0,66848.0,66922.0
1,Cochise,86389.872417,88135.403936,89174.875518,89599.598063,89231.315383,93743.122464,94523.384349,96640.324658,97301.905732,97368.183145,97939.684873,98767.428836,99699.714548,101150.212736,105251.217218,108494.089414,110279.448904,114039.017616,117166.404584,117138.259311,118046.859677,119515.184713,121501.982676,121871.191282,124804.944762,126458.961141,128622.592552,129522.360329,130566.559202,130296.108010,131283.962245,129782.885821,129393.307377,128943.265478,127086.360758,125983.716637,125413.888996,124093.629472,125373.964669,125252.558558,125718.0,126463.0,126648.0,127305.0
2,Coconino,76294.858824,79972.850851,83625.511819,81528.087822,82297.499665,85871.757708,88842.347589,91709.712830,94184.022011,95245.930892,96745.516713,98365.423833,99907.915793,102549.241376,104616.773086,105780.571125,108996.275279,112095.079307,115305.498759,115662.573807,117430.612291,122254.577909,124508.691799,126875.529634,128211.070950,128907.431492,130269.245089,132511.738548,132864.263599,133625.847190,134664.180713,134088.849097,134180.786517,135499.046588,139102.011176,141253.566100,142845.632491,143553.075467,144982.051829,146610.961971,145697.0,147434.0,149647.0,150722.0
3,Gila,37340.674475,37302.014138,37826.923670,38201.252623,36884.110094,36844.237558,38147.426869,38286.083672,39752.164605,39684.297996,40309.981753,41099.754486,41790.065537,42529.307495,43520.560002,44286.285659,45549.388640,47744.794606,49521.761573,50533.269836,51503.439245,51780.558552,51735.646630,52008.244264,52281.041723,52522.930249,54402.087126,54099.922317,54166.610765,53642.451431,53516.751862,53335.932389,53191.741000,53042.311320,53388.751407,53375.154811,53324.587549,53508.715830,53311.473102,53321.219048,53303.0,53525.0,53838.0,53800.0
4,Graham,23044.938624,23327.012817,24434.520377,24823.451538,24810.046871,24276.289584,25726.941791,26140.049693,26774.156863,26444.330923,26648.843177,27238.748426,27227.249868,28676.466710,29641.909014,28837.226976,29682.096101,30796.066369,32551.502946,33269.111933,33997.134140,33729.054021,33438.416755,33309.946057,34702.800027,34186.043879,34823.189254,35485.159737,36452.583527,37281.307016,37297.359626,37701.917165,37299.519985,37849.910784,38283.885259,38433.774227,38356.414543,38214.498918,38056.725059,38396.559390,38635.0,39025.0,39010.0,39656.0

Arizona Population Estimates Tail
==================================================
==================================================

,County,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
10,Pima,536415.409556,548539.165906,567742.576953,577492.133149,597810.099249,577370.136425,634451.428739,648936.150914,652795.172539,662026.430208,668187.014592,681275.452309,702734.222483,708195.474752,722506.048810,750399.362410,771217.771023,778343.914527,810475.139360,830120.583514,848374.534635,865701.035890,881529.662469,897837.644524,914010.752446,940003.520911,959474.191387,977258.097011,984031.514240,984273.898522,981015.274561,985318.032474,988997.389524,994015.844297,999686.901998,1.005920e+06,1.013296e+06,1.021153e+06,1.028511e+06,1.038205e+06,1045589.0,1058318.0,1.072298e+06,1080300.0
11,Pinal,91445.119073,93631.102078,95855.079268,97223.003126,99323.088162,101138.755001,105083.872084,108737.757348,112110.492801,114255.863505,116995.646360,120646.600423,124442.158553,129984.629099,135979.378224,143932.559472,150166.778654,157651.220516,166380.895428,175625.626682,182434.614838,186843.804845,190880.547874,204074.970932,219048.260014,250194.725342,304889.426636,333977.213080,358190.337762,364994.741599,375541.410134,380018.244122,381533.119461,382662.255203,385483.719878,3.879930e+05,3.926459e+05,4.009504e+05,4.094725e+05,4.193100e+05,428220.0,439128.0,4.539240e+05,467459.0
12,Santa Cruz,20513.285233,21268.897352,22228.947139,22388.159814,22747.809801,27470.384279,27948.091542,29752.126988,29320.528570,29701.037408,29873.356865,30265.105901,30801.583038,31159.411775,31907.982784,33238.580666,34260.247083,35395.627088,36672.132422,37784.452524,39304.768372,39224.418773,39656.732340,40527.787855,42038.392982,43808.991776,44928.566414,46518.844119,47016.490907,47384.057942,47401.118910,47393.439038,47462.682380,47387.679770,47156.081613,4.727941e+04,4.707535e+04,4.731820e+04,4.756906e+04,4.770660e+04,47787.0,48468.0,4.903900e+04,50004.0
13,Yavapai,68699.473060,69804.888002,73378.784903,75002.861074,83223.709261,83710.704155,95085.407963,99078.495066,99138.355850,105297.902561,108646.771728,111846.436661,115481.489207,120466.525750,126318.527315,133150.843480,139102.307513,147575.714993,155055.823935,163593.101573,169519.690427,173343.174408,176672.249315,182533.728765,187622.583249,196628.940166,202763.700650,211136.836784,212584.789098,211916.876177,210918.993889,211348.645538,211766.193611,213555.828107,215692.023142,2.181816e+05,2.219700e+05,2.259183e+05,2.296066e+05,2.331040e+05,237073.0,241173.0,2.453892e+05,248899.0
14,Yuma,77685.803691,78985.607690,82930.623910,81877.772614,87332.454273,92228.788674,90378.078778,92431.811910,98038.279811,102738.449732,108430.952204,111909.383049,115946.123739,121120.079635,125954.179190,129845.342513,134712.839086,141036.993988,149278.546394,156011.530996,164992.210547,164394.892105,167607.572315,172033.362503,177208.572120,183658.808535,189162.730108,192698.729987,193868.610294,194736.600883,195490.392566,197027.123733,198935.380519,200189.821988,199989.041020,2.000200e+05,2.005679e+05,2.005948e+05,2.010318e+05,2.024568e+05,204722.0,207318.0,2.099200e+05,214264.0

Arizona Weather Data Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164355 entries, 0 to 164354
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   County              164355 non-null  object
 1   Date                164355 non-null  object
 2   Latitude            164355 non-null  float64
 3   Longitude           164355 non-null  float64
 4   Temperature         164355 non-null  float64
 5   Visibility          34076 non-null   float64
 6   DewPoint            164355 non-null  float64
 7   FeelsLike           164355 non-null  float64
 8   TemperatureMinimum  164355 non-null  float64
 9   TemperatureMaximum  164355 non-null  float64
 10  Pressure            164355 non-null  float64
 11  SeaLevel            0 non-null       float64
 12  GroundLevel         0 non-null       float64
 13  Humidity            164355 non-null  float64
 14  WindSpeed           164355 non-null  float64
 15  WindDegree          164355 non-null  float64
 16  WindGust            22353 non-null   float64
 17  RainOneHour         36320 non-null   float64
 18  RainThreeHours      729 non-null     float64
 19  SnowOneHour         3543 non-null    float64
 20  SnowThreeHours      85 non-null      float64
 21  CloudsAll           164355 non-null  float64
dtypes: float64(20), object(2)
memory usage: 27.6+ MB

None

Arizona Weather Data Head
==================================================
==================================================

,County,Date,Latitude,Longitude,Temperature,Visibility,DewPoint,FeelsLike,TemperatureMinimum,TemperatureMaximum,Pressure,SeaLevel,GroundLevel,Humidity,WindSpeed,WindDegree,WindGust,RainOneHour,RainThreeHours,SnowOneHour,SnowThreeHours,CloudsAll
0,Apache,1994-01-01,35.531322,-109.378321,272.810417,NaN,264.115000,270.164167,272.030000,273.593750,1022.333333,NaN,NaN,49.916667,2.338333,125.250000,NaN,NaN,NaN,NaN,NaN,59.208333
1,Apache,1994-01-02,35.531322,-109.378321,273.887917,NaN,264.100833,269.936667,272.837083,274.801250,1023.833333,NaN,NaN,45.500000,4.014167,324.666667,NaN,NaN,NaN,NaN,NaN,39.083333
2,Apache,1994-01-03,35.531322,-109.378321,273.700000,NaN,261.728333,270.860000,272.896667,274.517083,1025.250000,NaN,NaN,37.500000,2.790833,180.916667,NaN,NaN,NaN,NaN,NaN,29.625000
3,Apache,1994-01-04,35.531322,-109.378321,275.560000,NaN,265.317083,272.930417,274.573333,276.552917,1022.208333,NaN,NaN,46.666667,2.876667,129.333333,NaN,NaN,NaN,NaN,NaN,22.000000
4,Apache,1994-01-05,35.531322,-109.378321,278.159167,NaN,264.769167,274.426250,277.310000,279.109167,1012.458333,NaN,NaN,34.875000,6.153750,233.166667,NaN,NaN,NaN,NaN,NaN,55.958333

Arizona Weather Data Tail
==================================================
==================================================

,County,Date,Latitude,Longitude,Temperature,Visibility,DewPoint,FeelsLike,TemperatureMinimum,TemperatureMaximum,Pressure,SeaLevel,GroundLevel,Humidity,WindSpeed,WindDegree,WindGust,RainOneHour,RainThreeHours,SnowOneHour,SnowThreeHours,CloudsAll
164350,Yuma,2023-12-27,32.652753,-113.953647,284.882083,NaN,278.777917,284.272083,283.844167,286.354167,1021.041667,NaN,NaN,67.541667,1.289583,188.458333,NaN,NaN,NaN,NaN,NaN,62.750000
164351,Yuma,2023-12-28,32.652753,-113.953647,285.651250,NaN,279.041250,285.023333,284.658333,287.139583,1020.541667,NaN,NaN,66.250000,1.021250,221.500000,NaN,NaN,NaN,NaN,NaN,48.833333
164352,Yuma,2023-12-29,32.652753,-113.953647,286.662083,NaN,278.756250,285.986250,285.391667,287.828750,1020.375000,NaN,NaN,62.000000,1.521250,172.125000,NaN,NaN,NaN,NaN,NaN,52.750000
164353,Yuma,2023-12-30,32.652753,-113.953647,287.997500,NaN,277.923750,286.882083,286.628750,288.836250,1017.166667,NaN,NaN,52.333333,1.575417,191.333333,NaN,NaN,NaN,NaN,NaN,46.375000
164354,Yuma,2023-12-31,32.652753,-113.953647,286.715417,NaN,280.161250,285.862083,285.803750,287.461667,1018.041667,NaN,NaN,65.708333,2.045833,248.916667,NaN,NaN,NaN,NaN,NaN,30.708333

California Cocci Case Count Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15312 entries, 0 to 15311
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   County  15312 non-null  object
 1   Cases   12676 non-null  float64
 2   Year    15312 non-null  int64
 3   Month   15312 non-null  int64
 4   Date    15312 non-null  object
dtypes: float64(1), int64(2), object(2)
memory usage: 598.2+ KB

None

California Cocci Case Count Head
==================================================
==================================================

    County  Cases  Year  Month        Date
0  Alameda    0.0  2001      1  2001-01-01
1  Alameda    0.0  2001      2  2001-02-01
2  Alameda    2.0  2001      3  2001-03-01
3  Alameda    2.0  2001      4  2001-04-01
4  Alameda    0.0  2001      5  2001-05-01

California Cocci Case Count Tail
==================================================
==================================================

      County  Cases  Year  Month        Date
15307   Yuba    NaN  2022      8  2022-08-01
15308   Yuba    NaN  2022      9  2022-09-01
15309   Yuba    NaN  2022     10  2022-10-01
15310   Yuba    NaN  2022     11  2022-11-01
15311   Yuba    NaN  2022     12  2022-12-01

California Population Estimates Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 61 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             288 non-null    int64
 1   Alameda          288 non-null    float64
 2   Alpine           288 non-null    float64
 3   Amador           288 non-null    float64
 4   Butte            288 non-null    float64
 5   Calaveras        288 non-null    float64
 6   Colusa           288 non-null    float64
 7   Contra Costa     288 non-null    float64
 8   Del Norte        288 non-null    float64
 9   El Dorado        288 non-null    float64
 10  Fresno           288 non-null    float64
 11  Glenn            288 non-null    float64
 12  Humboldt         288 non-null    float64
 13  Imperial         288 non-null    float64
 14  Inyo             288 non-null    float64
 15  Kern             288 non-null    float64
 16  Kings            288 non-null    float64
 17  Lake             288 non-null    float64
 18  Lassen           288 non-null    float64
 19  Los Angeles      288 non-null    float64
 20  Madera           288 non-null    float64
 21  Marin            288 non-null    float64
 22  Mariposa         288 non-null    float64
 23  Mendocino        288 non-null    float64
 24  Merced           288 non-null    float64
 25  Modoc            288 non-null    float64
 26  Mono             288 non-null    float64
 27  Monterey         288 non-null    float64
 28  Napa             288 non-null    float64
 29  Nevada           288 non-null    float64
 30  Orange           288 non-null    float64
 31  Placer           288 non-null    float64
 32  Plumas           288 non-null    float64
 33  Riverside        288 non-null    float64
 34  Sacramento       288 non-null    float64
 35  San Benito       288 non-null    float64
 36  San Bernardino   288 non-null    float64
 37  San Diego        288 non-null    float64
 38  San Francisco    288 non-null    float64
 39  San Joaquin      288 non-null    float64
 40  San Luis Obispo  288 non-null    float64
 41  San Mateo        288 non-null    float64
 42  Santa Barbara    288 non-null    float64
 43  Santa Clara      288 non-null    float64
 44  Santa Cruz       288 non-null    float64
 45  Shasta           288 non-null    float64
 46  Sierra           288 non-null    float64
 47  Siskiyou         288 non-null    float64
 48  Solano           288 non-null    float64
 49  Sonoma           288 non-null    float64
 50  Stanislaus       288 non-null    float64
 51  Sutter           288 non-null    float64
 52  Tehama           288 non-null    float64
 53  Trinity          288 non-null    float64
 54  Tulare           288 non-null    float64
 55  Tuolumne         288 non-null    float64
 56  Ventura          288 non-null    float64
 57  Yolo             288 non-null    float64
 58  Yuba             288 non-null    float64
 59  Month            288 non-null    int64
 60  date             288 non-null    object
dtypes: float64(58), int64(2), object(1)
memory usage: 137.4+ KB

None

California Population Estimates Head
==================================================
==================================================

,Year,Alameda,Alpine,Amador,Butte,Calaveras,Colusa,Contra Costa,Del Norte,El Dorado,Fresno,Glenn,Humboldt,Imperial,Inyo,Kern,Kings,Lake,Lassen,Los Angeles,Madera,Marin,Mariposa,Mendocino,Merced,Modoc,Mono,Monterey,Napa,Nevada,Orange,Placer,Plumas,Riverside,Sacramento,San Benito,San Bernardino,San Diego,San Francisco,San Joaquin,San Luis Obispo,San Mateo,Santa Barbara,Santa Clara,Santa Cruz,Shasta,Sierra,Siskiyou,Solano,Sonoma,Stanislaus,Sutter,Tehama,Trinity,Tulare,Tuolumne,Ventura,Yolo,Yuba,Month,date
0,2000,1449840.0,1209.0,35153.0,203807.0,40645.0,18817.0,952810.0,27440.0,157162.0,801288.0,26416.0,126462.0,142410.0,17955.0,663803.0,129835.0,58538.0,33719.0,9538191.0,123587.0,247520.0,17101.0,86407.0,212258.0,9406.0,12921.0,402990.0,124565.0,92520.0,2854513.0,251012.0,20754.0,1558985.0,1229940.0,53781.0,1718037.0,2827366.0,777885.0,567885.0,247839.0,707820.0,399990.0,1684947.0,255835.0,163615.0,3574.0,44218.0,396974.0,460421.0,449471.0,79192.0,56170.0,12980.0,368627.0,54658.0,756506.0,169835.0,60372.0,1,2000-01-01
1,2000,1449840.0,1209.0,35153.0,203807.0,40645.0,18817.0,952810.0,27440.0,157162.0,801288.0,26416.0,126462.0,142410.0,17955.0,663803.0,129835.0,58538.0,33719.0,9538191.0,123587.0,247520.0,17101.0,86407.0,212258.0,9406.0,12921.0,402990.0,124565.0,92520.0,2854513.0,251012.0,20754.0,1558985.0,1229940.0,53781.0,1718037.0,2827366.0,777885.0,567885.0,247839.0,707820.0,399990.0,1684947.0,255835.0,163615.0,3574.0,44218.0,396974.0,460421.0,449471.0,79192.0,56170.0,12980.0,368627.0,54658.0,756506.0,169835.0,60372.0,2,2000-02-01
2,2000,1449840.0,1209.0,35153.0,203807.0,40645.0,18817.0,952810.0,27440.0,157162.0,801288.0,26416.0,126462.0,142410.0,17955.0,663803.0,129835.0,58538.0,33719.0,9538191.0,123587.0,247520.0,17101.0,86407.0,212258.0,9406.0,12921.0,402990.0,124565.0,92520.0,2854513.0,251012.0,20754.0,1558985.0,1229940.0,53781.0,1718037.0,2827366.0,777885.0,567885.0,247839.0,707820.0,399990.0,1684947.0,255835.0,163615.0,3574.0,44218.0,396974.0,460421.0,449471.0,79192.0,56170.0,12980.0,368627.0,54658.0,756506.0,169835.0,60372.0,3,2000-03-01
3,2000,1449840.0,1209.0,35153.0,203807.0,40645.0,18817.0,952810.0,27440.0,157162.0,801288.0,26416.0,126462.0,142410.0,17955.0,663803.0,129835.0,58538.0,33719.0,9538191.0,123587.0,247520.0,17101.0,86407.0,212258.0,9406.0,12921.0,402990.0,124565.0,92520.0,2854513.0,251012.0,20754.0,1558985.0,1229940.0,53781.0,1718037.0,2827366.0,777885.0,567885.0,247839.0,707820.0,399990.0,1684947.0,255835.0,163615.0,3574.0,44218.0,396974.0,460421.0,449471.0,79192.0,56170.0,12980.0,368627.0,54658.0,756506.0,169835.0,60372.0,4,2000-04-01
4,2000,1449840.0,1209.0,35153.0,203807.0,40645.0,18817.0,952810.0,27440.0,157162.0,801288.0,26416.0,126462.0,142410.0,17955.0,663803.0,129835.0,58538.0,33719.0,9538191.0,123587.0,247520.0,17101.0,86407.0,212258.0,9406.0,12921.0,402990.0,124565.0,92520.0,2854513.0,251012.0,20754.0,1558985.0,1229940.0,53781.0,1718037.0,2827366.0,777885.0,567885.0,247839.0,707820.0,399990.0,1684947.0,255835.0,163615.0,3574.0,44218.0,396974.0,460421.0,449471.0,79192.0,56170.0,12980.0,368627.0,54658.0,756506.0,169835.0,60372.0,5,2000-05-01

California Population Estimates Tail
==================================================
==================================================

,Year,Alameda,Alpine,Amador,Butte,Calaveras,Colusa,Contra Costa,Del Norte,El Dorado,Fresno,Glenn,Humboldt,Imperial,Inyo,Kern,Kings,Lake,Lassen,Los Angeles,Madera,Marin,Mariposa,Mendocino,Merced,Modoc,Mono,Monterey,Napa,Nevada,Orange,Placer,Plumas,Riverside,Sacramento,San Benito,San Bernardino,San Diego,San Francisco,San Joaquin,San Luis Obispo,San Mateo,Santa Barbara,Santa Clara,Santa Cruz,Shasta,Sierra,Siskiyou,Solano,Sonoma,Stanislaus,Sutter,Tehama,Trinity,Tulare,Tuolumne,Ventura,Yolo,Yuba,Month,date
283,2023,1622188.0,1141.0,41811.0,207172.0,46565.0,22037.0,1155025.0,26589.0,192215.0,1017162.0,28129.0,133985.0,179057.0,18527.0,913820.0,152682.0,67878.0,28861.0,9663345.0,162858.0,254407.0,16919.0,89108.0,291920.0,8500.0,13066.0,430723.0,133216.0,102037.0,3135755.0,423561.0,19131.0,2492442.0,1584288.0,68175.0,2195611.0,3269973.0,808988.0,800965.0,281639.0,726353.0,441257.0,1877592.0,261547.0,180366.0,3200.0,42905.0,449218.0,481812.0,551430.0,97948.0,64896.0,15670.0,479468.0,54204.0,829590.0,220544.0,85722.0,8,2023-08-01
284,2023,1622188.0,1141.0,41811.0,207172.0,46565.0,22037.0,1155025.0,26589.0,192215.0,1017162.0,28129.0,133985.0,179057.0,18527.0,913820.0,152682.0,67878.0,28861.0,9663345.0,162858.0,254407.0,16919.0,89108.0,291920.0,8500.0,13066.0,430723.0,133216.0,102037.0,3135755.0,423561.0,19131.0,2492442.0,1584288.0,68175.0,2195611.0,3269973.0,808988.0,800965.0,281639.0,726353.0,441257.0,1877592.0,261547.0,180366.0,3200.0,42905.0,449218.0,481812.0,551430.0,97948.0,64896.0,15670.0,479468.0,54204.0,829590.0,220544.0,85722.0,9,2023-09-01
285,2023,1622188.0,1141.0,41811.0,207172.0,46565.0,22037.0,1155025.0,26589.0,192215.0,1017162.0,28129.0,133985.0,179057.0,18527.0,913820.0,152682.0,67878.0,28861.0,9663345.0,162858.0,254407.0,16919.0,89108.0,291920.0,8500.0,13066.0,430723.0,133216.0,102037.0,3135755.0,423561.0,19131.0,2492442.0,1584288.0,68175.0,2195611.0,3269973.0,808988.0,800965.0,281639.0,726353.0,441257.0,1877592.0,261547.0,180366.0,3200.0,42905.0,449218.0,481812.0,551430.0,97948.0,64896.0,15670.0,479468.0,54204.0,829590.0,220544.0,85722.0,10,2023-10-01
286,2023,1622188.0,1141.0,41811.0,207172.0,46565.0,22037.0,1155025.0,26589.0,192215.0,1017162.0,28129.0,133985.0,179057.0,18527.0,913820.0,152682.0,67878.0,28861.0,9663345.0,162858.0,254407.0,16919.0,89108.0,291920.0,8500.0,13066.0,430723.0,133216.0,102037.0,3135755.0,423561.0,19131.0,2492442.0,1584288.0,68175.0,2195611.0,3269973.0,808988.0,800965.0,281639.0,726353.0,441257.0,1877592.0,261547.0,180366.0,3200.0,42905.0,449218.0,481812.0,551430.0,97948.0,64896.0,15670.0,479468.0,54204.0,829590.0,220544.0,85722.0,11,2023-11-01
287,2023,1622188.0,1141.0,41811.0,207172.0,46565.0,22037.0,1155025.0,26589.0,192215.0,1017162.0,28129.0,133985.0,179057.0,18527.0,913820.0,152682.0,67878.0,28861.0,9663345.0,162858.0,254407.0,16919.0,89108.0,291920.0,8500.0,13066.0,430723.0,133216.0,102037.0,3135755.0,423561.0,19131.0,2492442.0,1584288.0,68175.0,2195611.0,3269973.0,808988.0,800965.0,281639.0,726353.0,441257.0,1877592.0,261547.0,180366.0,3200.0,42905.0,449218.0,481812.0,551430.0,97948.0,64896.0,15670.0,479468.0,54204.0,829590.0,220544.0,85722.0,12,2023-12-01

California Weather Data Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 385680 entries, 0 to 385679
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   County              385680 non-null  object
 1   Date                385680 non-null  object
 2   Latitude            385680 non-null  float64
 3   Longitude           385680 non-null  float64
 4   Temperature         385680 non-null  float64
 5   Visibility          157477 non-null  float64
 6   DewPoint            385680 non-null  float64
 7   FeelsLike           385680 non-null  float64
 8   TemperatureMinimum  385680 non-null  float64
 9   TemperatureMaximum  385680 non-null  float64
 10  Pressure            385680 non-null  float64
 11  SeaLevel            0 non-null       float64
 12  GroundLevel         0 non-null       float64
 13  Humidity            385680 non-null  float64
 14  WindSpeed           385680 non-null  float64
 15  WindDegree          385680 non-null  float64
 16  WindGust            89572 non-null   float64
 17  RainOneHour         83716 non-null   float64
 18  RainThreeHours      6146 non-null    float64
 19  SnowOneHour         5633 non-null    float64
 20  SnowThreeHours      61 non-null      float64
 21  CloudsAll           385680 non-null  float64
dtypes: float64(20), object(2)
memory usage: 64.7+ MB

None

California Weather Data Head
==================================================
==================================================

,County,Date,Latitude,Longitude,Temperature,Visibility,DewPoint,FeelsLike,TemperatureMinimum,TemperatureMaximum,Pressure,SeaLevel,GroundLevel,Humidity,WindSpeed,WindDegree,WindGust,RainOneHour,RainThreeHours,SnowOneHour,SnowThreeHours,CloudsAll
0,Alameda,2001-01-01,37.601689,-121.719546,8.390000,8342.857143,1.287917,7.492083,6.574167,10.485833,1019.333333,NaN,NaN,61.833333,2.207917,73.458333,NaN,NaN,NaN,NaN,NaN,17.708333
1,Alameda,2001-01-02,37.601689,-121.719546,8.551250,9766.666667,0.862500,7.215833,6.980417,10.632083,1023.583333,NaN,NaN,61.041667,2.477500,79.500000,NaN,NaN,NaN,NaN,NaN,5.166667
2,Alameda,2001-01-03,37.601689,-121.719546,10.125000,9111.111111,0.801667,9.011250,8.376667,12.681667,1026.916667,NaN,NaN,52.750000,2.368750,104.416667,NaN,NaN,NaN,NaN,NaN,0.000000
3,Alameda,2001-01-04,37.601689,-121.719546,10.165000,10000.000000,-1.030417,8.807500,8.111250,13.000000,1024.291667,NaN,NaN,46.041667,2.537083,76.291667,NaN,NaN,NaN,NaN,NaN,5.291667
4,Alameda,2001-01-05,37.601689,-121.719546,11.111667,9511.111111,0.440417,9.988750,8.653750,13.720417,1020.458333,NaN,NaN,48.083333,2.156667,85.458333,NaN,NaN,NaN,NaN,NaN,0.000000

California Weather Data Tail
==================================================
==================================================

,County,Date,Latitude,Longitude,Temperature,Visibility,DewPoint,FeelsLike,TemperatureMinimum,TemperatureMaximum,Pressure,SeaLevel,GroundLevel,Humidity,WindSpeed,WindDegree,WindGust,RainOneHour,RainThreeHours,SnowOneHour,SnowThreeHours,CloudsAll
385675,Yuba,2022-12-27,39.254703,-121.3999,11.722727,6919.428571,10.573030,11.321515,10.936364,13.400303,1011.636364,NaN,NaN,93.000000,9.092727,150.363636,16.3240,2.640667,NaN,NaN,NaN,100.000000
385676,Yuba,2022-12-28,39.254703,-121.3999,8.491667,10000.000000,6.945833,7.206250,7.870417,9.822083,1013.541667,NaN,NaN,90.416667,2.761667,110.541667,NaN,NaN,NaN,NaN,NaN,13.500000
385677,Yuba,2022-12-29,39.254703,-121.3999,7.817714,8556.171429,6.982571,6.495714,7.108571,8.674857,1013.942857,NaN,NaN,94.628571,2.160857,91.142857,NaN,0.682778,NaN,NaN,NaN,85.428571
385678,Yuba,2022-12-30,39.254703,-121.3999,10.258611,7048.638889,9.916111,8.996389,9.820556,11.912778,1012.861111,NaN,NaN,97.805556,6.930000,137.222222,13.2475,1.550000,NaN,NaN,NaN,98.611111
385679,Yuba,2022-12-31,39.254703,-121.3999,13.065600,8578.000000,12.123600,12.605200,12.373600,13.811600,1007.720000,NaN,NaN,94.040000,5.153600,211.960000,16.1200,2.122400,NaN,NaN,NaN,99.800000

Arizona CO Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307676 entries, 0 to 307675
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            307676 non-null  int64
 1   county_code           307676 non-null  int64
 2   site_number           307676 non-null  int64
 3   parameter_code        307676 non-null  int64
 4   poc                   307676 non-null  int64
 5   latitude              307676 non-null  float64
 6   longitude             307676 non-null  float64
 7   datum                 307676 non-null  object
 8   parameter             307676 non-null  object
 9   sample_duration_code  307676 non-null  object
 10  sample_duration       307676 non-null  object
 11  pollutant_standard    307676 non-null  object
 12  date_local            307676 non-null  object
 13  units_of_measure      307676 non-null  object
 14  event_type            307676 non-null  object
 15  observation_count     307676 non-null  int64
 16  observation_percent   307676 non-null  float64
 17  validity_indicator    307676 non-null  object
 18  arithmetic_mean       307676 non-null  float64
 19  first_max_value       307676 non-null  float64
 20  first_max_hour        307676 non-null  int64
 21  aqi                   153953 non-null  float64
 22  method_code           307665 non-null  float64
 23  method                307676 non-null  object
 24  local_site_name       307450 non-null  object
 25  site_address          307676 non-null  object
 26  state                 307676 non-null  object
 27  county                307676 non-null  object
 28  city                  307676 non-null  object
 29  cbsa_code             306419 non-null  float64
 30  cbsa                  306419 non-null  object
 31  date_of_last_change   307676 non-null  object
dtypes: float64(8), int64(7), object(17)
memory usage: 75.1+ MB

None

Arizona CO Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,13,16,42101,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-01,Parts per million,No Events,24,100.0,Y,4.237500,10.2,1,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2021-11-09
1,4,13,16,42101,1,33.49462,-112.13098,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,1993-01-01,Parts per million,No Events,19,79.0,Y,4.210526,8.6,5,92.0,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2023-02-05
2,4,13,16,42101,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-02,Parts per million,No Events,24,100.0,Y,2.495833,4.9,8,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2021-11-09
3,4,13,16,42101,1,33.49462,-112.13098,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,1993-01-02,Parts per million,No Events,24,100.0,Y,2.441667,3.2,8,36.0,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2023-02-05
4,4,13,16,42101,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-03,Parts per million,No Events,24,100.0,Y,1.112500,3.1,0,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2021-11-09

Arizona CO Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
307671,4,19,1014,42101,1,32.20739,-110.910619,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2023-12-29,Parts per million,No Events,24,100.0,Y,0.420833,0.600,0,7.0,554.0,INSTRUMENTAL - Gas Filter Correlation Thermo E...,22ND & ALVERNON,"22ND & ALVERNON, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-09
307672,4,19,1014,42101,1,32.20739,-110.910619,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2023-12-30,Parts per million,No Events,24,100.0,Y,0.294958,0.778,20,NaN,554.0,INSTRUMENTAL - Gas Filter Correlation Thermo E...,22ND & ALVERNON,"22ND & ALVERNON, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-03-08
307673,4,19,1014,42101,1,32.20739,-110.910619,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2023-12-30,Parts per million,No Events,24,100.0,Y,0.266667,0.400,19,5.0,554.0,INSTRUMENTAL - Gas Filter Correlation Thermo E...,22ND & ALVERNON,"22ND & ALVERNON, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-09
307674,4,19,1014,42101,1,32.20739,-110.910619,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2023-12-31,Parts per million,No Events,24,100.0,Y,0.374375,1.224,19,NaN,554.0,INSTRUMENTAL - Gas Filter Correlation Thermo E...,22ND & ALVERNON,"22ND & ALVERNON, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-03-08
307675,4,19,1014,42101,1,32.20739,-110.910619,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2023-12-31,Parts per million,No Events,24,100.0,Y,0.345833,0.500,20,6.0,554.0,INSTRUMENTAL - Gas Filter Correlation Thermo E...,22ND & ALVERNON,"22ND & ALVERNON, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-09

Arizona NO2 Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169936 entries, 0 to 169935
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            169936 non-null  int64
 1   county_code           169936 non-null  int64
 2   site_number           169936 non-null  int64
 3   parameter_code        169936 non-null  int64
 4   poc                   169936 non-null  int64
 5   latitude              169936 non-null  float64
 6   longitude             169936 non-null  float64
 7   datum                 169936 non-null  object
 8   parameter             169936 non-null  object
 9   sample_duration_code  169936 non-null  int64
 10  sample_duration       169936 non-null  object
 11  pollutant_standard    169936 non-null  object
 12  date_local            169936 non-null  object
 13  units_of_measure      169936 non-null  object
 14  event_type            169936 non-null  object
 15  observation_count     169936 non-null  int64
 16  observation_percent   169936 non-null  float64
 17  validity_indicator    169936 non-null  object
 18  arithmetic_mean       169936 non-null  float64
 19  first_max_value       169936 non-null  float64
 20  first_max_hour        169936 non-null  int64
 21  aqi                   169936 non-null  int64
 22  method_code           169936 non-null  int64
 23  method                169936 non-null  object
 24  local_site_name       169936 non-null  object
 25  site_address          169936 non-null  object
 26  state                 169936 non-null  object
 27  county                169936 non-null  object
 28  city                  169936 non-null  object
 29  cbsa_code             167824 non-null  float64
 30  cbsa                  167824 non-null  object
 31  date_of_last_change   169936 non-null  object
dtypes: float64(6), int64(10), object(16)
memory usage: 41.5+ MB

None

Arizona NO2 Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,19,19,42602,1,32.290075,-111.000651,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,1993-01-23,Parts per billion,No Events,24,100.0,Y,26.541667,41.0,9,39,42,INSTRUMENTAL - CHEMILUMINESCENCE,Pomona,"4591 N POMONA, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-23
1,4,19,19,42602,1,32.290075,-111.000651,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,1993-01-22,Parts per billion,No Events,12,50.0,N,34.333333,45.0,19,42,42,INSTRUMENTAL - CHEMILUMINESCENCE,Pomona,"4591 N POMONA, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-23
2,4,19,19,42602,1,32.290075,-111.000651,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,1993-01-22,Parts per billion,No Events,12,50.0,N,34.333333,45.0,19,42,42,INSTRUMENTAL - CHEMILUMINESCENCE,Pomona,"4591 N POMONA, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-23
3,4,19,19,42602,1,32.290075,-111.000651,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,1993-01-23,Parts per billion,No Events,24,100.0,Y,26.541667,41.0,9,39,42,INSTRUMENTAL - CHEMILUMINESCENCE,Pomona,"4591 N POMONA, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-23
4,4,19,19,42602,1,32.290075,-111.000651,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,1993-01-24,Parts per billion,No Events,24,100.0,Y,20.791667,38.0,9,36,42,INSTRUMENTAL - CHEMILUMINESCENCE,Pomona,"4591 N POMONA, TUCSON",Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-23

Arizona NO2 Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
169931,4,19,1036,42602,1,32.194671,-111.033167,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2023-12-29,Parts per billion,No Events,24,100.0,Y,18.358333,25.7,17,24,574,Instrumental - Chemiluminescence Thermo Electr...,Ted Walker Park,6751 north Casa Grande Hwy,Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-22
169932,4,19,1036,42602,1,32.194671,-111.033167,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2023-12-30,Parts per billion,No Events,24,100.0,Y,14.766667,24.0,21,23,574,Instrumental - Chemiluminescence Thermo Electr...,Ted Walker Park,6751 north Casa Grande Hwy,Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-22
169933,4,19,1036,42602,1,32.194671,-111.033167,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2023-12-30,Parts per billion,No Events,24,100.0,Y,14.766667,24.0,21,23,574,Instrumental - Chemiluminescence Thermo Electr...,Ted Walker Park,6751 north Casa Grande Hwy,Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-22
169934,4,19,1036,42602,1,32.194671,-111.033167,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2023-12-31,Parts per billion,No Events,24,100.0,Y,13.791667,21.0,2,20,574,Instrumental - Chemiluminescence Thermo Electr...,Ted Walker Park,6751 north Casa Grande Hwy,Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-22
169935,4,19,1036,42602,1,32.194671,-111.033167,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2023-12-31,Parts per billion,No Events,24,100.0,Y,13.791667,21.0,2,20,574,Instrumental - Chemiluminescence Thermo Electr...,Ted Walker Park,6751 north Casa Grande Hwy,Arizona,Pima,Tucson,46060.0,"Tucson, AZ",2024-05-22

Arizona Ozone Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1591371 entries, 0 to 1591370
Data columns (total 32 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   state_code            1591371 non-null  int64
 1   county_code           1591371 non-null  int64
 2   site_number           1591371 non-null  int64
 3   parameter_code        1591371 non-null  int64
 4   poc                   1591371 non-null  int64
 5   latitude              1591371 non-null  float64
 6   longitude             1591371 non-null  float64
 7   datum                 1591371 non-null  object
 8   parameter             1591371 non-null  object
 9   sample_duration_code  1591371 non-null  object
 10  sample_duration       1591371 non-null  object
 11  pollutant_standard    1591371 non-null  object
 12  date_local            1591371 non-null  object
 13  units_of_measure      1591371 non-null  object
 14  event_type            1591371 non-null  object
 15  observation_count     1591371 non-null  int64
 16  observation_percent   1591371 non-null  float64
 17  validity_indicator    1591371 non-null  object
 18  arithmetic_mean       1591371 non-null  float64
 19  first_max_value       1591371 non-null  float64
 20  first_max_hour        1591371 non-null  int64
 21  aqi                   1195063 non-null  float64
 22  method_code           1591332 non-null  float64
 23  method                1591371 non-null  object
 24  local_site_name       1587637 non-null  object
 25  site_address          1591371 non-null  object
 26  state                 1591371 non-null  object
 27  county                1591371 non-null  object
 28  city                  1591371 non-null  object
 29  cbsa_code             1569880 non-null  float64
 30  cbsa                  1569880 non-null  object
 31  date_of_last_change   1591371 non-null  object
dtypes: float64(8), int64(7), object(17)
memory usage: 388.5+ MB

None

Arizona Ozone Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,3,8001,44201,1,32.00941,-109.38906,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 1997,1993-01-03,Parts per million,No Events,24,100.0,Y,0.032708,0.039,2,36.0,47.0,INSTRUMENTAL - ULTRA VIOLET,Chiricahua NM - Entrance Station,CHIRICAHUA NATIONAL MOUMENT,Arizona,Cochise,Not in a city,43420.0,"Sierra Vista-Douglas, AZ",2023-02-05
1,4,3,8001,44201,1,32.00941,-109.38906,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,1993-01-01,Parts per million,No Events,23,96.0,Y,0.025043,0.030,1,NaN,47.0,INSTRUMENTAL - ULTRA VIOLET,Chiricahua NM - Entrance Station,CHIRICAHUA NATIONAL MOUMENT,Arizona,Cochise,Not in a city,43420.0,"Sierra Vista-Douglas, AZ",2018-07-20
2,4,3,8001,44201,1,32.00941,-109.38906,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,1993-01-02,Parts per million,No Events,23,96.0,Y,0.032217,0.040,12,NaN,47.0,INSTRUMENTAL - ULTRA VIOLET,Chiricahua NM - Entrance Station,CHIRICAHUA NATIONAL MOUMENT,Arizona,Cochise,Not in a city,43420.0,"Sierra Vista-Douglas, AZ",2018-07-20
3,4,3,8001,44201,1,32.00941,-109.38906,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,1993-01-03,Parts per million,No Events,24,100.0,Y,0.035333,0.042,10,NaN,47.0,INSTRUMENTAL - ULTRA VIOLET,Chiricahua NM - Entrance Station,CHIRICAHUA NATIONAL MOUMENT,Arizona,Cochise,Not in a city,43420.0,"Sierra Vista-Douglas, AZ",2018-07-20
4,4,3,8001,44201,1,32.00941,-109.38906,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 1997,1993-01-01,Parts per million,No Events,24,100.0,Y,0.024083,0.028,0,26.0,47.0,INSTRUMENTAL - ULTRA VIOLET,Chiricahua NM - Entrance Station,CHIRICAHUA NATIONAL MOUMENT,Arizona,Cochise,Not in a city,43420.0,"Sierra Vista-Douglas, AZ",2023-02-05

Arizona Ozone Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
1591366,4,13,7024,44201,1,33.508125,-111.83852,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2023-12-30,Parts per million,No Events,17,100.0,Y,0.029235,0.037,8,34.0,47.0,INSTRUMENTAL - ULTRA VIOLET,High School Air Monitoring Station,"4827 NORTH COUNTRY CLUB DRIVE, SCOTTSDALE, AZ ...",Arizona,Maricopa,Scottsdale,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-24
1591367,4,13,7024,44201,1,33.508125,-111.83852,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,2023-12-31,Parts per million,No Events,24,100.0,Y,0.025750,0.042,14,NaN,47.0,INSTRUMENTAL - ULTRA VIOLET,High School Air Monitoring Station,"4827 NORTH COUNTRY CLUB DRIVE, SCOTTSDALE, AZ ...",Arizona,Maricopa,Scottsdale,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-24
1591368,4,13,7024,44201,1,33.508125,-111.83852,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 1997,2023-12-31,Parts per million,No Events,19,79.0,Y,0.026789,0.037,10,34.0,47.0,INSTRUMENTAL - ULTRA VIOLET,High School Air Monitoring Station,"4827 NORTH COUNTRY CLUB DRIVE, SCOTTSDALE, AZ ...",Arizona,Maricopa,Scottsdale,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-24
1591369,4,13,7024,44201,1,33.508125,-111.83852,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 2008,2023-12-31,Parts per million,No Events,19,79.0,Y,0.026789,0.037,10,34.0,47.0,INSTRUMENTAL - ULTRA VIOLET,High School Air Monitoring Station,"4827 NORTH COUNTRY CLUB DRIVE, SCOTTSDALE, AZ ...",Arizona,Maricopa,Scottsdale,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-24
1591370,4,13,7024,44201,1,33.508125,-111.83852,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2023-12-31,Parts per million,No Events,12,71.0,N,0.029750,0.037,10,34.0,47.0,INSTRUMENTAL - ULTRA VIOLET,High School Air Monitoring Station,"4827 NORTH COUNTRY CLUB DRIVE, SCOTTSDALE, AZ ...",Arizona,Maricopa,Scottsdale,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-24

Arizona PM2.5 Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 875227 entries, 0 to 875226
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            875227 non-null  int64
 1   county_code           875227 non-null  int64
 2   site_number           875227 non-null  int64
 3   parameter_code        875227 non-null  int64
 4   poc                   875227 non-null  int64
 5   latitude              875227 non-null  float64
 6   longitude             875227 non-null  float64
 7   datum                 875227 non-null  object
 8   parameter             875227 non-null  object
 9   sample_duration_code  875227 non-null  object
 10  sample_duration       875227 non-null  object
 11  pollutant_standard    808042 non-null  object
 12  date_local            875227 non-null  object
 13  units_of_measure      875227 non-null  object
 14  event_type            875227 non-null  object
 15  observation_count     875227 non-null  int64
 16  observation_percent   875227 non-null  float64
 17  validity_indicator    875227 non-null  object
 18  arithmetic_mean       875227 non-null  float64
 19  first_max_value       875227 non-null  float64
 20  first_max_hour        875227 non-null  int64
 21  aqi                   808042 non-null  float64
 22  method_code           875227 non-null  int64
 23  method                875227 non-null  object
 24  local_site_name       875227 non-null  object
 25  site_address          875227 non-null  object
 26  state                 875227 non-null  object
 27  county                875227 non-null  object
 28  city                  875227 non-null  object
 29  cbsa_code             832775 non-null  float64
 30  cbsa                  832775 non-null  object
 31  date_of_last_change   875227 non-null  object
dtypes: float64(7), int64(8), object(17)
memory usage: 213.7+ MB

None

Arizona PM2.5 Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,5,1008,88101,1,35.206111,-111.652777,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 2006,1999-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.2,13.2,0,59.0,119,Andersen RAAS2.5-100 PM2.5 SAM w/WINS - GRAVIM...,FLAGSTAFF MIDDLE SCHOOL,755 W BONITO,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-10-24
1,4,5,1008,88101,1,35.206111,-111.652777,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 Annual 2006,1999-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.2,13.2,0,59.0,119,Andersen RAAS2.5-100 PM2.5 SAM w/WINS - GRAVIM...,FLAGSTAFF MIDDLE SCHOOL,755 W BONITO,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-10-24
2,4,5,1008,88101,1,35.206111,-111.652777,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 2012,1999-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.2,13.2,0,59.0,119,Andersen RAAS2.5-100 PM2.5 SAM w/WINS - GRAVIM...,FLAGSTAFF MIDDLE SCHOOL,755 W BONITO,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-10-24
3,4,5,1008,88101,1,35.206111,-111.652777,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 Annual 2012,1999-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.2,13.2,0,59.0,119,Andersen RAAS2.5-100 PM2.5 SAM w/WINS - GRAVIM...,FLAGSTAFF MIDDLE SCHOOL,755 W BONITO,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-10-24
4,4,5,1008,88101,1,35.206111,-111.652777,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 1997,1999-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.2,13.2,0,59.0,119,Andersen RAAS2.5-100 PM2.5 SAM w/WINS - GRAVIM...,FLAGSTAFF MIDDLE SCHOOL,755 W BONITO,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-10-24

Arizona PM2.5 Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
875222,4,12,8000,88101,3,34.2439,-113.5586,NAD83,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 24-hour 1997,2023-12-27,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.100000,1.1,0,6.0,638,Teledyne T640X at 16.67 LPM w/Network Data Ali...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
875223,4,12,8000,88101,3,34.2439,-113.5586,NAD83,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 Annual 1997,2023-12-27,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.100000,1.1,0,6.0,638,Teledyne T640X at 16.67 LPM w/Network Data Ali...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
875224,4,12,8000,88101,3,34.2439,-113.5586,NAD83,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 24-hour 2024,2023-12-27,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.100000,1.1,0,6.0,638,Teledyne T640X at 16.67 LPM w/Network Data Ali...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
875225,4,12,8000,88101,3,34.2439,-113.5586,NAD83,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 Annual 2024,2023-12-27,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.100000,1.1,0,6.0,638,Teledyne T640X at 16.67 LPM w/Network Data Ali...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
875226,4,12,8000,88101,3,34.2439,-113.5586,NAD83,PM2.5 - Local Conditions,1,1 HOUR,NaN,2023-12-28,Micrograms/cubic meter (LC),No Events,12,50.0,N,1.141667,1.7,0,NaN,638,Teledyne T640X at 16.67 LPM w/Network Data Ali...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-17

Arizona PM2.5 Non-Reference Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67037 entries, 0 to 67036
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state_code            67037 non-null  int64
 1   county_code           67037 non-null  int64
 2   site_number           67037 non-null  int64
 3   parameter_code        67037 non-null  int64
 4   poc                   67037 non-null  int64
 5   latitude              67037 non-null  float64
 6   longitude             67037 non-null  float64
 7   datum                 67037 non-null  object
 8   parameter             67037 non-null  object
 9   sample_duration_code  67037 non-null  object
 10  sample_duration       67037 non-null  object
 11  pollutant_standard    0 non-null      float64
 12  date_local            67037 non-null  object
 13  units_of_measure      67037 non-null  object
 14  event_type            67037 non-null  object
 15  observation_count     67037 non-null  int64
 16  observation_percent   67037 non-null  float64
 17  validity_indicator    67037 non-null  object
 18  arithmetic_mean       67037 non-null  float64
 19  first_max_value       67037 non-null  float64
 20  first_max_hour        67037 non-null  int64
 21  aqi                   57077 non-null  float64
 22  method_code           67037 non-null  int64
 23  method                67037 non-null  object
 24  local_site_name       56199 non-null  object
 25  site_address          67037 non-null  object
 26  state                 67037 non-null  object
 27  county                67037 non-null  object
 28  city                  67037 non-null  object
 29  cbsa_code             64405 non-null  float64
 30  cbsa                  64405 non-null  object
 31  date_of_last_change   67037 non-null  object
dtypes: float64(8), int64(8), object(16)
memory usage: 16.4+ MB

None

Arizona PM2.5 Non-Reference Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,5,2002,88502,1,36.080539,-112.155726,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,1993-01-02,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.7,1.7,0,9.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2024-05-21
1,4,5,2002,88502,1,36.080539,-112.155726,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,1993-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.6,1.6,0,9.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2024-05-21
2,4,5,2002,88502,1,36.080539,-112.155726,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,1993-01-16,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.6,1.6,0,9.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2024-05-21
3,4,5,2002,88502,1,36.080539,-112.155726,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,1993-01-20,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.2,1.2,0,7.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2024-05-21
4,4,5,2002,88502,1,36.080539,-112.155726,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,1993-01-23,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.9,0.9,0,5.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2024-05-21

Arizona PM2.5 Non-Reference Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
67032,4,1,8001,88502,1,34.058475,-109.441259,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2023-12-17,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.6,0.6,0,3.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
67033,4,1,8001,88502,1,34.058475,-109.441259,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2023-12-20,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.9,0.9,0,5.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
67034,4,1,8001,88502,1,34.058475,-109.441259,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2023-12-23,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.1,0.1,0,1.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
67035,4,1,8001,88502,1,34.058475,-109.441259,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2023-12-26,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.5,0.5,0,3.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
67036,4,1,8001,88502,1,34.058475,-109.441259,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2023-12-29,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.6,0.6,0,3.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03

Arizona PM10 Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612682 entries, 0 to 612681
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            612682 non-null  int64
 1   county_code           612682 non-null  int64
 2   site_number           612682 non-null  int64
 3   parameter_code        612682 non-null  int64
 4   poc                   612682 non-null  int64
 5   latitude              612682 non-null  float64
 6   longitude             612682 non-null  float64
 7   datum                 612682 non-null  object
 8   parameter             612682 non-null  object
 9   sample_duration_code  612682 non-null  object
 10  sample_duration       612682 non-null  object
 11  pollutant_standard    338228 non-null  object
 12  date_local            612682 non-null  object
 13  units_of_measure      612682 non-null  object
 14  event_type            612682 non-null  object
 15  observation_count     612682 non-null  int64
 16  observation_percent   612682 non-null  float64
 17  validity_indicator    612682 non-null  object
 18  arithmetic_mean       612682 non-null  float64
 19  first_max_value       612682 non-null  float64
 20  first_max_hour        612682 non-null  int64
 21  aqi                   338228 non-null  float64
 22  method_code           612682 non-null  int64
 23  method                612682 non-null  object
 24  local_site_name       608134 non-null  object
 25  site_address          612682 non-null  object
 26  state                 612682 non-null  object
 27  county                612682 non-null  object
 28  city                  612682 non-null  object
 29  cbsa_code             582786 non-null  float64
 30  cbsa                  582786 non-null  object
 31  date_of_last_change   612682 non-null  object
dtypes: float64(7), int64(8), object(17)
memory usage: 149.6+ MB

None

Arizona PM10 Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,5,1003,81102,1,35.207896,-111.655625,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,1993-01-01,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,10.0,10.0,0,9.0,4,LO-VOL-SA246B-DICHOT - GRAVIMETRIC,FLAGSTAFF THORPE PARK,FLAGSTAFF THORPE PK,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-05-22
1,4,5,1003,81102,1,35.207896,-111.655625,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,1993-01-07,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,5.0,5.0,0,5.0,4,LO-VOL-SA246B-DICHOT - GRAVIMETRIC,FLAGSTAFF THORPE PARK,FLAGSTAFF THORPE PK,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-05-22
2,4,5,1003,81102,1,35.207896,-111.655625,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,1993-01-25,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,31.0,31.0,0,29.0,4,LO-VOL-SA246B-DICHOT - GRAVIMETRIC,FLAGSTAFF THORPE PARK,FLAGSTAFF THORPE PK,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-05-22
3,4,5,1003,81102,1,35.207896,-111.655625,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,1993-01-31,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,9.0,9.0,0,8.0,4,LO-VOL-SA246B-DICHOT - GRAVIMETRIC,FLAGSTAFF THORPE PARK,FLAGSTAFF THORPE PK,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-05-22
4,4,5,1003,81102,1,35.207896,-111.655625,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,1993-02-06,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,27.0,27.0,0,25.0,4,LO-VOL-SA246B-DICHOT - GRAVIMETRIC,FLAGSTAFF THORPE PARK,FLAGSTAFF THORPE PK,Arizona,Coconino,Flagstaff,22380.0,"Flagstaff, AZ",2024-05-22

Arizona PM10 Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
612677,4,12,8000,81102,3,34.2439,-113.5586,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2023-12-26,Micrograms/cubic meter (25 C),No Events,24,100.0,Y,5.991667,11.5,19,NaN,639,Teledyne API T640X at 16.67 LPM w/Network Data...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
612678,4,12,8000,81102,3,34.2439,-113.5586,NAD83,PM10 Total 0-10um STP,X,24-HR BLK AVG,PM10 24-hour 2006,2023-12-26,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,5.000000,5.0,23,5.0,639,Teledyne API T640X at 16.67 LPM w/Network Data...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-22
612679,4,12,8000,81102,3,34.2439,-113.5586,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2023-12-27,Micrograms/cubic meter (25 C),No Events,24,100.0,Y,5.666667,13.9,13,NaN,639,Teledyne API T640X at 16.67 LPM w/Network Data...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21
612680,4,12,8000,81102,3,34.2439,-113.5586,NAD83,PM10 Total 0-10um STP,X,24-HR BLK AVG,PM10 24-hour 2006,2023-12-27,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,5.000000,5.0,23,5.0,639,Teledyne API T640X at 16.67 LPM w/Network Data...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-22
612681,4,12,8000,81102,3,34.2439,-113.5586,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2023-12-28,Micrograms/cubic meter (25 C),No Events,12,50.0,N,5.291667,8.6,0,NaN,639,Teledyne API T640X at 16.67 LPM w/Network Data...,ALAMO LAKE,ALAMO LAKE STATE PARK,Arizona,La Paz,Wenden,NaN,NaN,2024-05-21

Arizona SO2 Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289156 entries, 0 to 289155
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            289156 non-null  int64
 1   county_code           289156 non-null  int64
 2   site_number           289156 non-null  int64
 3   parameter_code        289156 non-null  int64
 4   poc                   289156 non-null  int64
 5   latitude              289156 non-null  float64
 6   longitude             289156 non-null  float64
 7   datum                 289156 non-null  object
 8   parameter             289156 non-null  object
 9   sample_duration_code  289156 non-null  object
 10  sample_duration       289156 non-null  object
 11  pollutant_standard    274618 non-null  object
 12  date_local            289156 non-null  object
 13  units_of_measure      289156 non-null  object
 14  event_type            289156 non-null  object
 15  observation_count     289156 non-null  int64
 16  observation_percent   289156 non-null  float64
 17  validity_indicator    289156 non-null  object
 18  arithmetic_mean       289156 non-null  float64
 19  first_max_value       289156 non-null  float64
 20  first_max_hour        289156 non-null  int64
 21  aqi                   136168 non-null  float64
 22  method_code           289156 non-null  int64
 23  method                289156 non-null  object
 24  local_site_name       286568 non-null  object
 25  site_address          289156 non-null  object
 26  state                 289156 non-null  object
 27  county                289156 non-null  object
 28  city                  289156 non-null  object
 29  cbsa_code             286392 non-null  float64
 30  cbsa                  286392 non-null  object
 31  date_of_last_change   289156 non-null  object
dtypes: float64(7), int64(8), object(17)
memory usage: 70.6+ MB

None

Arizona SO2 Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,5,8100,42401,1,36.077814,-112.129551,WGS84,Sulfur dioxide,7,24 HOUR,SO2 24-hour 1971,1993-01-16,Parts per billion,No Events,1,100.0,Y,0.0,0.0,0,NaN,811,IMPROVE Module D with Cyclone Inlet-Quartz Fil...,NaN,Indian Gardens,Arizona,Coconino,Not in a city,22380.0,"Flagstaff, AZ",2021-11-10
1,4,5,8100,42401,1,36.077814,-112.129551,WGS84,Sulfur dioxide,7,24 HOUR,SO2 24-hour 1971,1993-01-02,Parts per billion,No Events,1,100.0,Y,0.0,0.0,0,NaN,811,IMPROVE Module D with Cyclone Inlet-Quartz Fil...,NaN,Indian Gardens,Arizona,Coconino,Not in a city,22380.0,"Flagstaff, AZ",2021-11-10
2,4,5,8100,42401,1,36.077814,-112.129551,WGS84,Sulfur dioxide,7,24 HOUR,SO2 Annual 1971,1993-01-02,Parts per billion,No Events,1,100.0,Y,0.0,0.0,0,NaN,811,IMPROVE Module D with Cyclone Inlet-Quartz Fil...,NaN,Indian Gardens,Arizona,Coconino,Not in a city,22380.0,"Flagstaff, AZ",2021-11-10
3,4,5,8100,42401,1,36.077814,-112.129551,WGS84,Sulfur dioxide,7,24 HOUR,SO2 24-hour 1971,1993-01-06,Parts per billion,No Events,1,100.0,Y,0.0,0.0,0,NaN,811,IMPROVE Module D with Cyclone Inlet-Quartz Fil...,NaN,Indian Gardens,Arizona,Coconino,Not in a city,22380.0,"Flagstaff, AZ",2021-11-10
4,4,5,8100,42401,1,36.077814,-112.129551,WGS84,Sulfur dioxide,7,24 HOUR,SO2 Annual 1971,1993-01-06,Parts per billion,No Events,1,100.0,Y,0.0,0.0,0,NaN,811,IMPROVE Module D with Cyclone Inlet-Quartz Fil...,NaN,Indian Gardens,Arizona,Coconino,Not in a city,22380.0,"Flagstaff, AZ",2021-11-10

Arizona SO2 Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
289151,4,13,9812,42401,1,33.4265,-112.11821,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2023-12-31,Parts per billion,No Events,8,100.0,Y,0.2375,1.0,11,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,DURANGO COMPLEX,2702 RC ESTERBROOKS BLVD,Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-09
289152,4,13,9812,42401,1,33.4265,-112.11821,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2023-12-27,Parts per billion,No Events,8,100.0,Y,0.6875,1.3,8,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,DURANGO COMPLEX,2702 RC ESTERBROOKS BLVD,Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-09
289153,4,13,9812,42401,1,33.4265,-112.11821,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2023-12-28,Parts per billion,No Events,8,100.0,Y,1.0125,1.6,8,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,DURANGO COMPLEX,2702 RC ESTERBROOKS BLVD,Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-09
289154,4,13,9812,42401,1,33.4265,-112.11821,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2023-12-29,Parts per billion,No Events,8,100.0,Y,1.3500,2.3,8,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,DURANGO COMPLEX,2702 RC ESTERBROOKS BLVD,Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-09
289155,4,13,9812,42401,1,33.4265,-112.11821,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2023-12-30,Parts per billion,No Events,8,100.0,Y,0.1500,0.6,2,NaN,100,INSTRUMENTAL - ULTRAVIOLET FLUORESCENCE,DURANGO COMPLEX,2702 RC ESTERBROOKS BLVD,Arizona,Maricopa,Phoenix,38060.0,"Phoenix-Mesa-Scottsdale, AZ",2024-05-09

Arizona TSP Data 1993-2023 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61292 entries, 0 to 61291
Data columns (total 32 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   state_code            61292 non-null  int64
 1   county_code           61292 non-null  int64
 2   site_number           61292 non-null  int64
 3   parameter_code        61292 non-null  int64
 4   poc                   61292 non-null  int64
 5   latitude              61292 non-null  float64
 6   longitude             61292 non-null  float64
 7   datum                 61292 non-null  object
 8   parameter             61292 non-null  object
 9   sample_duration_code  61292 non-null  int64
 10  sample_duration       61292 non-null  object
 11  pollutant_standard    0 non-null      float64
 12  date_local            61292 non-null  object
 13  units_of_measure      61292 non-null  object
 14  event_type            61292 non-null  object
 15  observation_count     61292 non-null  int64
 16  observation_percent   61292 non-null  float64
 17  validity_indicator    61292 non-null  object
 18  arithmetic_mean       61292 non-null  float64
 19  first_max_value       61292 non-null  float64
 20  first_max_hour        61292 non-null  int64
 21  aqi                   0 non-null      float64
 22  method_code           61292 non-null  int64
 23  method                61292 non-null  object
 24  local_site_name       49985 non-null  object
 25  site_address          61292 non-null  object
 26  state                 61292 non-null  object
 27  county                61292 non-null  object
 28  city                  61292 non-null  object
 29  cbsa_code             58672 non-null  float64
 30  cbsa                  58672 non-null  object
 31  date_of_last_change   61292 non-null  object
dtypes: float64(8), int64(9), object(15)
memory usage: 15.0+ MB

None

Arizona TSP Data 1993-2023 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,4,5,2002,85101,1,36.080539,-112.155726,WGS84,PM10 - LC,7,24 HOUR,NaN,1993-01-02,Micrograms/cubic meter (LC),No Events,1,100.0,Y,6.88921,6.88921,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2014-07-30
1,4,5,2002,85101,1,36.080539,-112.155726,WGS84,PM10 - LC,7,24 HOUR,NaN,1993-01-06,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.77432,1.77432,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2014-07-30
2,4,5,2002,85101,1,36.080539,-112.155726,WGS84,PM10 - LC,7,24 HOUR,NaN,1993-01-09,Micrograms/cubic meter (LC),No Events,1,100.0,Y,2.09137,2.09137,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2014-07-30
3,4,5,2002,85101,1,36.080539,-112.155726,WGS84,PM10 - LC,7,24 HOUR,NaN,1993-01-13,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.85610,0.85610,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2014-07-30
4,4,5,2002,85101,1,36.080539,-112.155726,WGS84,PM10 - LC,7,24 HOUR,NaN,1993-01-16,Micrograms/cubic meter (LC),No Events,1,100.0,Y,2.28830,2.28830,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,NaN,HOPI POINT GRAND CANYON NATIONAL PARK,Arizona,Coconino,Grand Canyon,22380.0,"Flagstaff, AZ",2014-07-30

Arizona TSP Data 1993-2023 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
61287,4,1,8001,85101,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-17,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.008,1.008,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
61288,4,1,8001,85101,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-20,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.573,1.573,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
61289,4,1,8001,85101,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-23,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.518,0.518,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
61290,4,1,8001,85101,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-26,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.544,0.544,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03
61291,4,1,8001,85101,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-29,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.796,0.796,0,NaN,808,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city,NaN,NaN,2024-09-03

California CO Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1203054 entries, 0 to 1203053
Data columns (total 32 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   state_code            1203054 non-null  int64
 1   county_code           1203054 non-null  int64
 2   site_number           1203054 non-null  int64
 3   parameter_code        1203054 non-null  int64
 4   poc                   1203054 non-null  int64
 5   latitude              1203054 non-null  float64
 6   longitude             1203054 non-null  float64
 7   datum                 1203054 non-null  object
 8   parameter             1203054 non-null  object
 9   sample_duration_code  1203054 non-null  object
 10  sample_duration       1203054 non-null  object
 11  pollutant_standard    1203054 non-null  object
 12  date_local            1203054 non-null  object
 13  units_of_measure      1203054 non-null  object
 14  event_type            1203054 non-null  object
 15  observation_count     1203054 non-null  int64
 16  observation_percent   1203054 non-null  float64
 17  validity_indicator    1203054 non-null  object
 18  arithmetic_mean       1203054 non-null  float64
 19  first_max_value       1203054 non-null  float64
 20  first_max_hour        1203054 non-null  int64
 21  aqi                   601552 non-null   float64
 22  method_code           1203048 non-null  float64
 23  method                1203054 non-null  object
 24  local_site_name       1177738 non-null  object
 25  site_address          1203054 non-null  object
 26  state                 1203054 non-null  object
 27  county                1203054 non-null  object
 28  city                  1203054 non-null  object
 29  cbsa_code             1190821 non-null  float64
 30  cbsa                  1190821 non-null  object
 31  date_of_last_change   1203054 non-null  object
dtypes: float64(8), int64(7), object(17)
memory usage: 293.7+ MB

None

California CO Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,83,1008,42101,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-08,Parts per million,No Events,11,46.0,Y,0.054545,0.2,18,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2021-11-09
1,6,83,1008,42101,1,34.942872,-120.435611,NAD83,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2000-03-08,Parts per million,No Events,6,25.0,Y,0.100000,0.1,18,1.0,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2023-02-05
2,6,83,1008,42101,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-09,Parts per million,No Events,23,96.0,Y,0.360870,0.8,17,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2021-11-09
3,6,83,1008,42101,1,34.942872,-120.435611,NAD83,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2000-03-09,Parts per million,No Events,24,100.0,Y,0.245833,0.7,20,8.0,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2023-02-05
4,6,83,1008,42101,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-10,Parts per million,No Events,21,88.0,Y,0.719048,1.2,8,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2021-11-09

California CO Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
1203049,6,83,2004,42101,1,34.63782,-120.45750,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2022-12-28,Parts per million,No Events,24,100.0,Y,-0.087500,0.0,13,0.0,93.0,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,Lompoc H Street,"128 S 'H' ST, LOMPOC",California,Santa Barbara,Lompoc,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-09
1203050,6,83,2004,42101,1,34.63782,-120.45750,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2022-12-29,Parts per million,No Events,24,100.0,Y,-0.050000,0.0,1,0.0,93.0,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,Lompoc H Street,"128 S 'H' ST, LOMPOC",California,Santa Barbara,Lompoc,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-09
1203051,6,83,2004,42101,1,34.63782,-120.45750,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2022-12-31,Parts per million,No Events,22,92.0,Y,-0.177273,-0.1,19,NaN,93.0,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,Lompoc H Street,"128 S 'H' ST, LOMPOC",California,Santa Barbara,Lompoc,42200.0,"Santa Maria-Santa Barbara, CA",2023-05-17
1203052,6,83,2004,42101,1,34.63782,-120.45750,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2022-12-31,Parts per million,No Events,24,100.0,Y,-0.187500,-0.1,0,0.0,93.0,INSTRUMENTAL - GAS FILTER CORRELATION CO ANALYZER,Lompoc H Street,"128 S 'H' ST, LOMPOC",California,Santa Barbara,Lompoc,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-09
1203053,6,37,2,42101,1,34.13650,-117.92391,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2022-09-30,Parts per million,No Events,2,8.0,Y,0.450000,0.5,1,6.0,NaN,-,Azusa,"803 N. LOREN AVE., AZUSA",California,Los Angeles,Azusa,31080.0,"Los Angeles-Long Beach-Anaheim, CA",2024-09-08

California NO2 Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1674068 entries, 0 to 1674067
Data columns (total 32 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   state_code            1674068 non-null  int64
 1   county_code           1674068 non-null  int64
 2   site_number           1674068 non-null  int64
 3   parameter_code        1674068 non-null  int64
 4   poc                   1674068 non-null  int64
 5   latitude              1674068 non-null  float64
 6   longitude             1674068 non-null  float64
 7   datum                 1674068 non-null  object
 8   parameter             1674068 non-null  object
 9   sample_duration_code  1674068 non-null  int64
 10  sample_duration       1674068 non-null  object
 11  pollutant_standard    1674068 non-null  object
 12  date_local            1674068 non-null  object
 13  units_of_measure      1674068 non-null  object
 14  event_type            1674068 non-null  object
 15  observation_count     1674068 non-null  int64
 16  observation_percent   1674068 non-null  float64
 17  validity_indicator    1674068 non-null  object
 18  arithmetic_mean       1674068 non-null  float64
 19  first_max_value       1674068 non-null  float64
 20  first_max_hour        1674068 non-null  int64
 21  aqi                   1674068 non-null  int64
 22  method_code           1674068 non-null  int64
 23  method                1674068 non-null  object
 24  local_site_name       1665482 non-null  object
 25  site_address          1674068 non-null  object
 26  state                 1674068 non-null  object
 27  county                1674068 non-null  object
 28  city                  1674068 non-null  object
 29  cbsa_code             1672844 non-null  float64
 30  cbsa                  1672844 non-null  object
 31  date_of_last_change   1674068 non-null  object
dtypes: float64(6), int64(10), object(16)
memory usage: 408.7+ MB

None

California NO2 Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,83,1008,42602,1,34.942872,-120.435611,NAD83,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2000-03-01,Parts per billion,No Events,23,96.0,Y,15.608696,32.0,19,30,74,INSTRUMENTAL - CHEMILUMINESCENCE,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-23
1,6,83,1008,42602,1,34.942872,-120.435611,NAD83,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2000-03-01,Parts per billion,No Events,23,96.0,Y,15.608696,32.0,19,30,74,INSTRUMENTAL - CHEMILUMINESCENCE,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-23
2,6,83,1008,42602,1,34.942872,-120.435611,NAD83,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2000-03-02,Parts per billion,No Events,23,96.0,Y,13.391304,22.0,18,21,74,INSTRUMENTAL - CHEMILUMINESCENCE,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-23
3,6,83,1008,42602,1,34.942872,-120.435611,NAD83,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2000-03-02,Parts per billion,No Events,23,96.0,Y,13.391304,22.0,18,21,74,INSTRUMENTAL - CHEMILUMINESCENCE,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-23
4,6,83,1008,42602,1,34.942872,-120.435611,NAD83,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2000-03-03,Parts per billion,No Events,23,96.0,Y,12.956522,31.0,20,29,74,INSTRUMENTAL - CHEMILUMINESCENCE,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-23

California NO2 Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
1674063,6,75,5,42602,1,37.765946,-122.399044,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2022-12-29,Parts per billion,No Events,23,96.0,Y,12.013043,27.4,17,25,74,INSTRUMENTAL - CHEMILUMINESCENCE,San Francisco,10 ARKANSAS ST.,California,San Francisco,San Francisco,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-22
1674064,6,75,5,42602,1,37.765946,-122.399044,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2022-12-30,Parts per billion,No Events,23,96.0,Y,2.421739,5.2,0,5,74,INSTRUMENTAL - CHEMILUMINESCENCE,San Francisco,10 ARKANSAS ST.,California,San Francisco,San Francisco,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-22
1674065,6,75,5,42602,1,37.765946,-122.399044,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2022-12-30,Parts per billion,No Events,23,96.0,Y,2.421739,5.2,0,5,74,INSTRUMENTAL - CHEMILUMINESCENCE,San Francisco,10 ARKANSAS ST.,California,San Francisco,San Francisco,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-22
1674066,6,75,5,42602,1,37.765946,-122.399044,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 Annual 1971,2022-12-31,Parts per billion,No Events,23,96.0,Y,6.539130,17.0,8,16,74,INSTRUMENTAL - CHEMILUMINESCENCE,San Francisco,10 ARKANSAS ST.,California,San Francisco,San Francisco,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-22
1674067,6,75,5,42602,1,37.765946,-122.399044,WGS84,Nitrogen dioxide (NO2),1,1 HOUR,NO2 1-hour 2010,2022-12-31,Parts per billion,No Events,23,96.0,Y,6.539130,17.0,8,16,74,INSTRUMENTAL - CHEMILUMINESCENCE,San Francisco,10 ARKANSAS ST.,California,San Francisco,San Francisco,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-22

California Ozone Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5370774 entries, 0 to 5370773
Data columns (total 32 columns):
 #   Column                Dtype
---  ------                -----
 0   state_code            int64
 1   county_code           int64
 2   site_number           int64
 3   parameter_code        int64
 4   poc                   int64
 5   latitude              float64
 6   longitude             float64
 7   datum                 object
 8   parameter             object
 9   sample_duration_code  object
 10  sample_duration       object
 11  pollutant_standard    object
 12  date_local            object
 13  units_of_measure      object
 14  event_type            object
 15  observation_count     int64
 16  observation_percent   float64
 17  validity_indicator    object
 18  arithmetic_mean       float64
 19  first_max_value       float64
 20  first_max_hour        int64
 21  aqi                   float64
 22  method_code           float64
 23  method                object
 24  local_site_name       object
 25  site_address          object
 26  state                 object
 27  county                object
 28  city                  object
 29  cbsa_code             float64
 30  cbsa                  object
 31  date_of_last_change   object
dtypes: float64(8), int64(7), object(17)
memory usage: 1.3+ GB

None

California Ozone Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,83,1007,44201,1,34.948034,-120.435441,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,2000-01-01,Parts per million,No Events,23,96.0,Y,0.024348,0.035,14,NaN,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Santa Maria-500 S. Broadway,"500 S BROADWAY, SANTA MARIA",California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2022-01-29
1,6,83,1007,44201,1,34.948034,-120.435441,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 1997,2000-01-01,Parts per million,No Events,24,100.0,Y,0.023125,0.032,10,30.0,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Santa Maria-500 S. Broadway,"500 S BROADWAY, SANTA MARIA",California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2023-02-05
2,6,83,1007,44201,1,34.948034,-120.435441,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 2008,2000-01-01,Parts per million,No Events,24,100.0,Y,0.023125,0.032,10,30.0,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Santa Maria-500 S. Broadway,"500 S BROADWAY, SANTA MARIA",California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2023-02-05
3,6,83,1007,44201,1,34.948034,-120.435441,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2000-01-01,Parts per million,No Events,17,100.0,Y,0.025882,0.032,10,30.0,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Santa Maria-500 S. Broadway,"500 S BROADWAY, SANTA MARIA",California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2023-02-05
4,6,83,1007,44201,1,34.948034,-120.435441,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,2000-01-02,Parts per million,No Events,23,96.0,Y,0.027000,0.037,14,NaN,87.0,INSTRUMENTAL - ULTRA VIOLET ABSORPTION,Santa Maria-500 S. Broadway,"500 S BROADWAY, SANTA MARIA",California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2022-01-29

California Ozone Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
5370769,6,89,9,44201,1,40.689253,-122.402194,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-12-30,Parts per million,No Events,17,100.0,Y,0.008647,0.019,7,18.0,199.0,Instrumental - Chemiluminescence API Model 265...,Shasta Lake - Lake Blvd,"13791 Lake Blvd, Shasta Lake, CA",California,Shasta,Shasta Lake,39820.0,"Redding, CA",2024-05-25
5370770,6,89,9,44201,1,40.689253,-122.402194,WGS84,Ozone,1,1 HOUR,Ozone 1-hour 1979,2022-12-31,Parts per million,No Events,24,100.0,Y,0.013583,0.025,23,NaN,199.0,Instrumental - Chemiluminescence API Model 265...,Shasta Lake - Lake Blvd,"13791 Lake Blvd, Shasta Lake, CA",California,Shasta,Shasta Lake,39820.0,"Redding, CA",2024-05-25
5370771,6,89,9,44201,1,40.689253,-122.402194,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 1997,2022-12-31,Parts per million,No Events,19,79.0,Y,0.014421,0.020,8,19.0,199.0,Instrumental - Chemiluminescence API Model 265...,Shasta Lake - Lake Blvd,"13791 Lake Blvd, Shasta Lake, CA",California,Shasta,Shasta Lake,39820.0,"Redding, CA",2024-05-25
5370772,6,89,9,44201,1,40.689253,-122.402194,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-Hour 2008,2022-12-31,Parts per million,No Events,19,79.0,Y,0.014421,0.020,8,19.0,199.0,Instrumental - Chemiluminescence API Model 265...,Shasta Lake - Lake Blvd,"13791 Lake Blvd, Shasta Lake, CA",California,Shasta,Shasta Lake,39820.0,"Redding, CA",2024-05-25
5370773,6,89,9,44201,1,40.689253,-122.402194,WGS84,Ozone,W,8-HR RUN AVG BEGIN HOUR,Ozone 8-hour 2015,2022-12-31,Parts per million,No Events,12,71.0,N,0.015333,0.020,8,19.0,199.0,Instrumental - Chemiluminescence API Model 265...,Shasta Lake - Lake Blvd,"13791 Lake Blvd, Shasta Lake, CA",California,Shasta,Shasta Lake,39820.0,"Redding, CA",2024-05-25

California PM2.5 Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3397307 entries, 0 to 3397306
Data columns (total 32 columns):
 #   Column                Dtype
---  ------                -----
 0   state_code            int64
 1   county_code           int64
 2   site_number           int64
 3   parameter_code        int64
 4   poc                   int64
 5   latitude              float64
 6   longitude             float64
 7   datum                 object
 8   parameter             object
 9   sample_duration_code  object
 10  sample_duration       object
 11  pollutant_standard    object
 12  date_local            object
 13  units_of_measure      object
 14  event_type            object
 15  observation_count     int64
 16  observation_percent   float64
 17  validity_indicator    object
 18  arithmetic_mean       float64
 19  first_max_value       float64
 20  first_max_hour        int64
 21  aqi                   float64
 22  method_code           int64
 23  method                object
 24  local_site_name       object
 25  site_address          object
 26  state                 object
 27  county                object
 28  city                  object
 29  cbsa_code             float64
 30  cbsa                  object
 31  date_of_last_change   object
dtypes: float64(7), int64(8), object(17)
memory usage: 829.4+ MB

None

California PM2.5 Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,1,7,88101,1,37.687526,-121.784217,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 2006,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.9,13.9,0,60.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Livermore,793 Rincon Ave.,California,Alameda,Livermore,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-19
1,6,1,7,88101,1,37.687526,-121.784217,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 Annual 2006,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.9,13.9,0,60.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Livermore,793 Rincon Ave.,California,Alameda,Livermore,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-19
2,6,1,7,88101,1,37.687526,-121.784217,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 2012,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.9,13.9,0,60.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Livermore,793 Rincon Ave.,California,Alameda,Livermore,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-19
3,6,1,7,88101,1,37.687526,-121.784217,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 Annual 2012,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.9,13.9,0,60.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Livermore,793 Rincon Ave.,California,Alameda,Livermore,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-19
4,6,1,7,88101,1,37.687526,-121.784217,WGS84,PM2.5 - Local Conditions,7,24 HOUR,PM25 24-hour 1997,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,13.9,13.9,0,60.0,120,Andersen RAAS2.5-300 PM2.5 SEQ w/WINS - GRAVIM...,Livermore,793 Rincon Ave.,California,Alameda,Livermore,41860.0,"San Francisco-Oakland-Hayward, CA",2024-05-19

California PM2.5 Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
3397302,6,27,1023,88101,21,37.362137,-118.417478,WGS84,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 Annual 2012,2020-12-31,Micrograms/cubic meter (LC),Events Included,1,100.0,Y,9.7,9.7,0,52.0,736,Teledyne T640 at 5.0 LPM (Corrected) - Broadba...,Bishop Tribe EMO,50 TU SU LANE,California,Inyo,Bishop,13860.0,"Bishop, CA",2024-08-07
3397303,6,27,1023,88101,21,37.362137,-118.417478,WGS84,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 24-hour 1997,2020-12-31,Micrograms/cubic meter (LC),Events Included,1,100.0,Y,9.7,9.7,0,52.0,736,Teledyne T640 at 5.0 LPM (Corrected) - Broadba...,Bishop Tribe EMO,50 TU SU LANE,California,Inyo,Bishop,13860.0,"Bishop, CA",2024-08-07
3397304,6,27,1023,88101,21,37.362137,-118.417478,WGS84,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 Annual 1997,2020-12-31,Micrograms/cubic meter (LC),Events Included,1,100.0,Y,9.7,9.7,0,52.0,736,Teledyne T640 at 5.0 LPM (Corrected) - Broadba...,Bishop Tribe EMO,50 TU SU LANE,California,Inyo,Bishop,13860.0,"Bishop, CA",2024-08-07
3397305,6,27,1023,88101,21,37.362137,-118.417478,WGS84,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 24-hour 2024,2020-12-31,Micrograms/cubic meter (LC),Events Included,1,100.0,Y,9.7,9.7,0,52.0,736,Teledyne T640 at 5.0 LPM (Corrected) - Broadba...,Bishop Tribe EMO,50 TU SU LANE,California,Inyo,Bishop,13860.0,"Bishop, CA",2024-08-07
3397306,6,27,1023,88101,21,37.362137,-118.417478,WGS84,PM2.5 - Local Conditions,X,24-HR BLK AVG,PM25 Annual 2024,2020-12-31,Micrograms/cubic meter (LC),Events Included,1,100.0,Y,9.7,9.7,0,52.0,736,Teledyne T640 at 5.0 LPM (Corrected) - Broadba...,Bishop Tribe EMO,50 TU SU LANE,California,Inyo,Bishop,13860.0,"Bishop, CA",2024-08-07

California PM2.5 Non-Reference Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510371 entries, 0 to 510370
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            510371 non-null  int64
 1   county_code           510371 non-null  int64
 2   site_number           510371 non-null  int64
 3   parameter_code        510371 non-null  int64
 4   poc                   510371 non-null  int64
 5   latitude              510371 non-null  float64
 6   longitude             510371 non-null  float64
 7   datum                 510371 non-null  object
 8   parameter             510371 non-null  object
 9   sample_duration_code  510371 non-null  object
 10  sample_duration       510371 non-null  object
 11  pollutant_standard    0 non-null       float64
 12  date_local            510371 non-null  object
 13  units_of_measure      510371 non-null  object
 14  event_type            510371 non-null  object
 15  observation_count     510371 non-null  int64
 16  observation_percent   510371 non-null  float64
 17  validity_indicator    510371 non-null  object
 18  arithmetic_mean       510371 non-null  float64
 19  first_max_value       510371 non-null  float64
 20  first_max_hour        510371 non-null  int64
 21  aqi                   291754 non-null  float64
 22  method_code           510371 non-null  int64
 23  method                510371 non-null  object
 24  local_site_name       507225 non-null  object
 25  site_address          510371 non-null  object
 26  state                 510371 non-null  object
 27  county                510371 non-null  object
 28  city                  510371 non-null  object
 29  cbsa_code             453717 non-null  float64
 30  cbsa                  453717 non-null  object
 31  date_of_last_change   510371 non-null  object
dtypes: float64(8), int64(8), object(16)
memory usage: 124.6+ MB

None

California PM2.5 Non-Reference Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,71,9010,88502,1,34.193925,-116.914063,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2000-01-12,Micrograms/cubic meter (LC),No Events,1,100.0,Y,2.5,2.5,0,14.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,San Gorgonio Wilderness,California,San Bernardino,Not in a city,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
1,6,71,9010,88502,1,34.193925,-116.914063,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,6.3,6.3,0,35.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,San Gorgonio Wilderness,California,San Bernardino,Not in a city,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
2,6,71,9010,88502,1,34.193925,-116.914063,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2000-01-15,Micrograms/cubic meter (LC),No Events,1,100.0,Y,4.5,4.5,0,25.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,San Gorgonio Wilderness,California,San Bernardino,Not in a city,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
3,6,71,9010,88502,1,34.193925,-116.914063,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2000-01-19,Micrograms/cubic meter (LC),No Events,1,100.0,Y,3.3,3.3,0,18.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,San Gorgonio Wilderness,California,San Bernardino,Not in a city,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
4,6,71,9010,88502,1,34.193925,-116.914063,WGS84,Acceptable PM2.5 AQI & Speciation Mass,7,24 HOUR,NaN,2000-01-22,Micrograms/cubic meter (LC),No Events,1,100.0,Y,4.9,4.9,0,27.0,707,IMPROVE Module A with Cyclone Inlet-Teflon Fil...,NaN,San Gorgonio Wilderness,California,San Bernardino,Not in a city,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21

California PM2.5 Non-Reference Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
510366,6,89,4,88502,3,40.55013,-122.38092,NAD83,Acceptable PM2.5 AQI & Speciation Mass,X,24-HR BLK AVG,NaN,2022-06-22,Micrograms/cubic meter (LC),No Events,1,100.0,Y,4.800000,4.8,23,27.0,171,Met-one BAM-1022 W/PM2.5 SCC - Beta Attenuation,Redding - Health Department,"HLTH CTR-2630 BRESLAUER WAY, REDDING",California,Shasta,Redding,39820.0,"Redding, CA",2024-11-15
510367,6,89,4,88502,3,40.55013,-122.38092,NAD83,Acceptable PM2.5 AQI & Speciation Mass,1,1 HOUR,NaN,2022-06-23,Micrograms/cubic meter (LC),No Events,24,100.0,Y,5.833333,16.0,9,NaN,171,Met-one BAM-1022 W/PM2.5 SCC - Beta Attenuation,Redding - Health Department,"HLTH CTR-2630 BRESLAUER WAY, REDDING",California,Shasta,Redding,39820.0,"Redding, CA",2024-11-15
510368,6,89,4,88502,3,40.55013,-122.38092,NAD83,Acceptable PM2.5 AQI & Speciation Mass,X,24-HR BLK AVG,NaN,2022-06-23,Micrograms/cubic meter (LC),No Events,1,100.0,Y,5.800000,5.8,23,32.0,171,Met-one BAM-1022 W/PM2.5 SCC - Beta Attenuation,Redding - Health Department,"HLTH CTR-2630 BRESLAUER WAY, REDDING",California,Shasta,Redding,39820.0,"Redding, CA",2024-11-15
510369,6,89,4,88502,3,40.55013,-122.38092,NAD83,Acceptable PM2.5 AQI & Speciation Mass,1,1 HOUR,NaN,2022-06-24,Micrograms/cubic meter (LC),No Events,23,96.0,Y,4.695652,12.0,7,NaN,171,Met-one BAM-1022 W/PM2.5 SCC - Beta Attenuation,Redding - Health Department,"HLTH CTR-2630 BRESLAUER WAY, REDDING",California,Shasta,Redding,39820.0,"Redding, CA",2024-11-15
510370,6,89,4,88502,3,40.55013,-122.38092,NAD83,Acceptable PM2.5 AQI & Speciation Mass,X,24-HR BLK AVG,NaN,2022-06-24,Micrograms/cubic meter (LC),No Events,1,100.0,Y,4.600000,4.6,23,26.0,171,Met-one BAM-1022 W/PM2.5 SCC - Beta Attenuation,Redding - Health Department,"HLTH CTR-2630 BRESLAUER WAY, REDDING",California,Shasta,Redding,39820.0,"Redding, CA",2024-11-15

California PM10 Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 974009 entries, 0 to 974008
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            974009 non-null  int64
 1   county_code           974009 non-null  int64
 2   site_number           974009 non-null  int64
 3   parameter_code        974009 non-null  int64
 4   poc                   974009 non-null  int64
 5   latitude              974009 non-null  float64
 6   longitude             974009 non-null  float64
 7   datum                 974009 non-null  object
 8   parameter             974009 non-null  object
 9   sample_duration_code  974009 non-null  object
 10  sample_duration       974009 non-null  object
 11  pollutant_standard    578228 non-null  object
 12  date_local            974009 non-null  object
 13  units_of_measure      974009 non-null  object
 14  event_type            974009 non-null  object
 15  observation_count     974009 non-null  int64
 16  observation_percent   974009 non-null  float64
 17  validity_indicator    974009 non-null  object
 18  arithmetic_mean       974009 non-null  float64
 19  first_max_value       974009 non-null  float64
 20  first_max_hour        974009 non-null  int64
 21  aqi                   578228 non-null  float64
 22  method_code           974009 non-null  int64
 23  method                974009 non-null  object
 24  local_site_name       972951 non-null  object
 25  site_address          974009 non-null  object
 26  state                 974009 non-null  object
 27  county                974009 non-null  object
 28  city                  974009 non-null  object
 29  cbsa_code             905463 non-null  float64
 30  cbsa                  905463 non-null  object
 31  date_of_last_change   974009 non-null  object
dtypes: float64(7), int64(8), object(17)
memory usage: 237.8+ MB

None

California PM10 Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,83,1008,81102,1,34.942872,-120.435611,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2000-03-01,Micrograms/cubic meter (25 C),No Events,24,100.0,Y,12.583333,28.0,19,NaN,79,INSTRUMENTAL-R&P SA246B-INLET - TEOM-GRAVIMETRIC,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-22
1,6,83,1008,81102,1,34.942872,-120.435611,NAD83,PM10 Total 0-10um STP,X,24-HR BLK AVG,PM10 24-hour 2006,2000-03-01,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,12.000000,12.0,23,11.0,79,INSTRUMENTAL-R&P SA246B-INLET - TEOM-GRAVIMETRIC,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-22
2,6,83,1008,81102,1,34.942872,-120.435611,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2000-03-02,Micrograms/cubic meter (25 C),No Events,24,100.0,Y,18.041667,49.0,10,NaN,79,INSTRUMENTAL-R&P SA246B-INLET - TEOM-GRAVIMETRIC,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-22
3,6,83,1008,81102,1,34.942872,-120.435611,NAD83,PM10 Total 0-10um STP,X,24-HR BLK AVG,PM10 24-hour 2006,2000-03-02,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,18.000000,18.0,23,17.0,79,INSTRUMENTAL-R&P SA246B-INLET - TEOM-GRAVIMETRIC,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-22
4,6,83,1008,81102,1,34.942872,-120.435611,NAD83,PM10 Total 0-10um STP,1,1 HOUR,NaN,2000-03-03,Micrograms/cubic meter (25 C),No Events,24,100.0,Y,12.541667,45.0,20,NaN,79,INSTRUMENTAL-R&P SA246B-INLET - TEOM-GRAVIMETRIC,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria,42200.0,"Santa Maria-Santa Barbara, CA",2024-05-22

California PM10 Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
974004,6,65,2002,81102,6,33.70853,-116.21537,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,2022-03-21,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,20.0,20.0,0,19.0,63,HI-VOL SA/GMW-1200 - GRAVIMETRIC,Indio,"46-990 JACKSON ST., INDIO",California,Riverside,Indio,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
974005,6,65,2002,81102,6,33.70853,-116.21537,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,2022-03-27,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,25.0,25.0,0,23.0,63,HI-VOL SA/GMW-1200 - GRAVIMETRIC,Indio,"46-990 JACKSON ST., INDIO",California,Riverside,Indio,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
974006,6,65,2002,81102,6,33.70853,-116.21537,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,2022-04-02,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,22.0,22.0,0,20.0,63,HI-VOL SA/GMW-1200 - GRAVIMETRIC,Indio,"46-990 JACKSON ST., INDIO",California,Riverside,Indio,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
974007,6,65,2002,81102,6,33.70853,-116.21537,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,2022-04-08,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,23.0,23.0,0,21.0,63,HI-VOL SA/GMW-1200 - GRAVIMETRIC,Indio,"46-990 JACKSON ST., INDIO",California,Riverside,Indio,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21
974008,6,65,2002,81102,6,33.70853,-116.21537,WGS84,PM10 Total 0-10um STP,7,24 HOUR,PM10 24-hour 2006,2022-04-14,Micrograms/cubic meter (25 C),No Events,1,100.0,Y,35.0,35.0,0,32.0,63,HI-VOL SA/GMW-1200 - GRAVIMETRIC,Indio,"46-990 JACKSON ST., INDIO",California,Riverside,Indio,40140.0,"Riverside-San Bernardino-Ontario, CA",2024-05-21

California SO2 Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1116565 entries, 0 to 1116564
Data columns (total 32 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   state_code            1116565 non-null  int64
 1   county_code           1116565 non-null  int64
 2   site_number           1116565 non-null  int64
 3   parameter_code        1116565 non-null  int64
 4   poc                   1116565 non-null  int64
 5   latitude              1116565 non-null  float64
 6   longitude             1116565 non-null  float64
 7   datum                 1116565 non-null  object
 8   parameter             1116565 non-null  object
 9   sample_duration_code  1116565 non-null  object
 10  sample_duration       1116565 non-null  object
 11  pollutant_standard    1072175 non-null  object
 12  date_local            1116565 non-null  object
 13  units_of_measure      1116565 non-null  object
 14  event_type            1116565 non-null  object
 15  observation_count     1116565 non-null  int64
 16  observation_percent   1116565 non-null  float64
 17  validity_indicator    1116565 non-null  object
 18  arithmetic_mean       1116565 non-null  float64
 19  first_max_value       1116565 non-null  float64
 20  first_max_hour        1116565 non-null  int64
 21  aqi                   539144 non-null   float64
 22  method_code           1116565 non-null  int64
 23  method                1116565 non-null  object
 24  local_site_name       1112768 non-null  object
 25  site_address          1116565 non-null  object
 26  state                 1116565 non-null  object
 27  county                1116565 non-null  object
 28  city                  1116565 non-null  object
 29  cbsa_code             1116565 non-null  int64
 30  cbsa                  1116565 non-null  object
 31  date_of_last_change   1116565 non-null  object
dtypes: float64(6), int64(9), object(17)
memory usage: 272.6+ MB

None

California SO2 Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,83,1013,42401,1,34.725352,-120.428717,NAD83,Sulfur dioxide,1,1 HOUR,SO2 Annual 1971,2000-01-01,Parts per billion,No Events,23,96.0,Y,1.434783,3.0,3,4.0,39,INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC,Lompoc HSP,"HS & P FACILITY-500 M SW, LOMPOC",California,Santa Barbara,Lompoc,42200,"Santa Maria-Santa Barbara, CA",2021-11-09
1,6,83,1013,42401,1,34.725352,-120.428717,NAD83,Sulfur dioxide,1,1 HOUR,SO2 1-hour 2010,2000-01-01,Parts per billion,No Events,23,96.0,Y,1.434783,3.0,3,4.0,39,INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC,Lompoc HSP,"HS & P FACILITY-500 M SW, LOMPOC",California,Santa Barbara,Lompoc,42200,"Santa Maria-Santa Barbara, CA",2021-11-09
2,6,83,1013,42401,1,34.725352,-120.428717,NAD83,Sulfur dioxide,X,24-HR BLK AVG,SO2 24-hour 1971,2000-01-01,Parts per billion,No Events,1,100.0,Y,1.400000,1.4,23,NaN,39,INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC,Lompoc HSP,"HS & P FACILITY-500 M SW, LOMPOC",California,Santa Barbara,Lompoc,42200,"Santa Maria-Santa Barbara, CA",2023-02-05
3,6,83,1013,42401,1,34.725352,-120.428717,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2000-01-01,Parts per billion,No Events,7,88.0,Y,1.414286,2.0,5,NaN,39,INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC,Lompoc HSP,"HS & P FACILITY-500 M SW, LOMPOC",California,Santa Barbara,Lompoc,42200,"Santa Maria-Santa Barbara, CA",2023-02-05
4,6,83,1013,42401,1,34.725352,-120.428717,NAD83,Sulfur dioxide,1,1 HOUR,SO2 Annual 1971,2000-01-02,Parts per billion,No Events,23,96.0,Y,1.043478,2.0,9,3.0,39,INSTRUMENTAL - ULTRA VIOLET STIMULATED FLUORESCNC,Lompoc HSP,"HS & P FACILITY-500 M SW, LOMPOC",California,Santa Barbara,Lompoc,42200,"Santa Maria-Santa Barbara, CA",2021-11-09

California SO2 Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
1116560,6,25,5,42401,3,32.67618,-115.48307,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2022-12-30,Parts per billion,No Events,7,88.0,Y,0.157143,0.4,17,NaN,560,INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE,Calexico-Ethel Street,"1029 ETHEL ST, CALEXICO HIGH SCHOOL",California,Imperial,Calexico,20940,"El Centro, CA",2024-05-09
1116561,6,25,5,42401,3,32.67618,-115.48307,NAD83,Sulfur dioxide,1,1 HOUR,SO2 Annual 1971,2022-12-31,Parts per billion,No Events,23,96.0,Y,0.047826,0.3,20,0.0,560,INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE,Calexico-Ethel Street,"1029 ETHEL ST, CALEXICO HIGH SCHOOL",California,Imperial,Calexico,20940,"El Centro, CA",2023-03-08
1116562,6,25,5,42401,3,32.67618,-115.48307,NAD83,Sulfur dioxide,1,1 HOUR,SO2 1-hour 2010,2022-12-31,Parts per billion,No Events,23,96.0,Y,0.047826,0.3,20,0.0,560,INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE,Calexico-Ethel Street,"1029 ETHEL ST, CALEXICO HIGH SCHOOL",California,Imperial,Calexico,20940,"El Centro, CA",2023-03-08
1116563,6,25,5,42401,3,32.67618,-115.48307,NAD83,Sulfur dioxide,X,24-HR BLK AVG,SO2 24-hour 1971,2022-12-31,Parts per billion,No Events,1,100.0,Y,0.000000,0.0,23,NaN,560,INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE,Calexico-Ethel Street,"1029 ETHEL ST, CALEXICO HIGH SCHOOL",California,Imperial,Calexico,20940,"El Centro, CA",2024-05-09
1116564,6,25,5,42401,3,32.67618,-115.48307,NAD83,Sulfur dioxide,Y,3-HR BLK AVG,SO2 3-hour 1971,2022-12-31,Parts per billion,No Events,7,88.0,Y,0.028571,0.1,14,NaN,560,INSTRUMENTAL - Pulsed Fluorescent 43C-TLE/43i-TLE,Calexico-Ethel Street,"1029 ETHEL ST, CALEXICO HIGH SCHOOL",California,Imperial,Calexico,20940,"El Centro, CA",2024-05-09

California TSP Data 2000-2022 Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501523 entries, 0 to 501522
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            501523 non-null  int64
 1   county_code           501523 non-null  int64
 2   site_number           501523 non-null  int64
 3   parameter_code        501523 non-null  int64
 4   poc                   501523 non-null  int64
 5   latitude              501523 non-null  float64
 6   longitude             501523 non-null  float64
 7   datum                 501523 non-null  object
 8   parameter             501523 non-null  object
 9   sample_duration_code  501523 non-null  int64
 10  sample_duration       501523 non-null  object
 11  pollutant_standard    0 non-null       float64
 12  date_local            501523 non-null  object
 13  units_of_measure      501523 non-null  object
 14  event_type            501523 non-null  object
 15  observation_count     501523 non-null  int64
 16  observation_percent   501523 non-null  float64
 17  validity_indicator    501523 non-null  object
 18  arithmetic_mean       501523 non-null  float64
 19  first_max_value       501523 non-null  float64
 20  first_max_hour        501523 non-null  int64
 21  aqi                   0 non-null       float64
 22  method_code           501523 non-null  int64
 23  method                501523 non-null  object
 24  local_site_name       496638 non-null  object
 25  site_address          501523 non-null  object
 26  state                 501523 non-null  object
 27  county                501523 non-null  object
 28  city                  501523 non-null  object
 29  cbsa_code             455322 non-null  float64
 30  cbsa                  455322 non-null  object
 31  date_of_last_change   501523 non-null  object
dtypes: float64(8), int64(9), object(15)
memory usage: 122.4+ MB

None

California TSP Data 2000-2022 Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,53.0,53.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
1,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-07,Micrograms/cubic meter (LC),No Events,1,100.0,Y,85.0,85.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
2,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-13,Micrograms/cubic meter (LC),No Events,1,100.0,Y,68.0,68.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
3,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-19,Micrograms/cubic meter (LC),No Events,1,100.0,Y,25.0,25.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
4,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-25,Micrograms/cubic meter (LC),No Events,1,100.0,Y,8.0,8.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11

California TSP Data 2000-2022 Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
501518,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-27,Micrograms/cubic meter (LC),No Events,24,100.0,Y,25.883333,36.4,13,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501519,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-28,Micrograms/cubic meter (LC),No Events,24,100.0,Y,9.587500,19.0,22,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501520,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-29,Micrograms/cubic meter (LC),No Events,24,100.0,Y,20.591667,30.1,12,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501521,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-30,Micrograms/cubic meter (LC),No Events,24,100.0,Y,18.970833,29.3,22,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501522,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-31,Micrograms/cubic meter (LC),No Events,24,100.0,Y,14.850000,23.6,9,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05

California and Arizona Air Pollutants Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 501523 entries, 0 to 501522
Data columns (total 32 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   state_code            501523 non-null  int64
 1   county_code           501523 non-null  int64
 2   site_number           501523 non-null  int64
 3   parameter_code        501523 non-null  int64
 4   poc                   501523 non-null  int64
 5   latitude              501523 non-null  float64
 6   longitude             501523 non-null  float64
 7   datum                 501523 non-null  object
 8   parameter             501523 non-null  object
 9   sample_duration_code  501523 non-null  int64
 10  sample_duration       501523 non-null  object
 11  pollutant_standard    0 non-null       float64
 12  date_local            501523 non-null  object
 13  units_of_measure      501523 non-null  object
 14  event_type            501523 non-null  object
 15  observation_count     501523 non-null  int64
 16  observation_percent   501523 non-null  float64
 17  validity_indicator    501523 non-null  object
 18  arithmetic_mean       501523 non-null  float64
 19  first_max_value       501523 non-null  float64
 20  first_max_hour        501523 non-null  int64
 21  aqi                   0 non-null       float64
 22  method_code           501523 non-null  int64
 23  method                501523 non-null  object
 24  local_site_name       496638 non-null  object
 25  site_address          501523 non-null  object
 26  state                 501523 non-null  object
 27  county                501523 non-null  object
 28  city                  501523 non-null  object
 29  cbsa_code             455322 non-null  float64
 30  cbsa                  455322 non-null  object
 31  date_of_last_change   501523 non-null  object
dtypes: float64(8), int64(9), object(15)
memory usage: 122.4+ MB

None

California and Arizona Air Pollutants Head
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
0,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-01,Micrograms/cubic meter (LC),No Events,1,100.0,Y,53.0,53.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
1,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-07,Micrograms/cubic meter (LC),No Events,1,100.0,Y,85.0,85.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
2,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-13,Micrograms/cubic meter (LC),No Events,1,100.0,Y,68.0,68.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
3,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-19,Micrograms/cubic meter (LC),No Events,1,100.0,Y,25.0,25.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11
4,6,99,5,85101,1,37.642165,-120.994212,NAD83,PM10 - LC,7,24 HOUR,NaN,2000-01-25,Micrograms/cubic meter (LC),No Events,1,100.0,Y,8.0,8.0,0,NaN,63,HI-VOL-SA/GMW1200 - GRAVIMETRIC,Modesto-14th Street,"814 14TH ST., MODESTO",California,Stanislaus,Modesto,33700.0,"Modesto, CA",2013-06-11

California and Arizona Air Pollutants Tail
==================================================
==================================================

,state_code,county_code,site_number,parameter_code,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city,cbsa_code,cbsa,date_of_last_change
501518,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-27,Micrograms/cubic meter (LC),No Events,24,100.0,Y,25.883333,36.4,13,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501519,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-28,Micrograms/cubic meter (LC),No Events,24,100.0,Y,9.587500,19.0,22,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501520,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-29,Micrograms/cubic meter (LC),No Events,24,100.0,Y,20.591667,30.1,12,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501521,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-30,Micrograms/cubic meter (LC),No Events,24,100.0,Y,18.970833,29.3,22,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05
501522,6,73,1022,85101,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-31,Micrograms/cubic meter (LC),No Events,24,100.0,Y,14.850000,23.6,9,NaN,239,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon,41740.0,"San Diego-Carlsbad, CA",2023-05-05

California Air Pollutants Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14747671 entries, 0 to 14747670
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   poc                   int64
 1   latitude              float64
 2   longitude             float64
 3   datum                 object
 4   parameter             object
 5   sample_duration_code  object
 6   sample_duration       object
 7   pollutant_standard    object
 8   date_local            object
 9   units_of_measure      object
 10  event_type            object
 11  observation_count     int64
 12  observation_percent   float64
 13  validity_indicator    object
 14  arithmetic_mean       float64
 15  first_max_value       float64
 16  first_max_hour        int64
 17  aqi                   float64
 18  method_code           float64
 19  method                object
 20  local_site_name       object
 21  site_address          object
 22  state                 object
 23  county                object
 24  city                  object
dtypes: float64(7), int64(3), object(15)
memory usage: 2.7+ GB

None

California Air Pollutants Head
==================================================
==================================================

,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city
0,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-08,Parts per million,No Events,11,46.0,Y,0.054545,0.2,18,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria
1,1,34.942872,-120.435611,NAD83,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2000-03-08,Parts per million,No Events,6,25.0,Y,0.100000,0.1,18,1.0,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria
2,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-09,Parts per million,No Events,23,96.0,Y,0.360870,0.8,17,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria
3,1,34.942872,-120.435611,NAD83,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,2000-03-09,Parts per million,No Events,24,100.0,Y,0.245833,0.7,20,8.0,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria
4,1,34.942872,-120.435611,NAD83,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,2000-03-10,Parts per million,No Events,21,88.0,Y,0.719048,1.2,8,NaN,67.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,Santa Maria,906 S BROADWAY - SANTA MARIA,California,Santa Barbara,Santa Maria

California Air Pollutants Tail
==================================================
==================================================

,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city
14747666,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-27,Micrograms/cubic meter (LC),No Events,24,100.0,Y,25.883333,36.4,13,NaN,239.0,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon
14747667,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-28,Micrograms/cubic meter (LC),No Events,24,100.0,Y,9.587500,19.0,22,NaN,239.0,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon
14747668,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-29,Micrograms/cubic meter (LC),No Events,24,100.0,Y,20.591667,30.1,12,NaN,239.0,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon
14747669,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-30,Micrograms/cubic meter (LC),No Events,24,100.0,Y,18.970833,29.3,22,NaN,239.0,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon
14747670,3,32.789565,-116.944308,NAD83,PM10 - LC,1,1 HOUR,NaN,2022-12-31,Micrograms/cubic meter (LC),No Events,24,100.0,Y,14.850000,23.6,9,NaN,239.0,Teledyne API T640X at 16.67 LPM - Broadband sp...,El Cajon - Lexington Elementary School,533 First Street,California,San Diego,El Cajon

Arizona Air Pollutants Info
==================================================
==================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3974377 entries, 0 to 3974376
Data columns (total 25 columns):
 #   Column                Dtype
---  ------                -----
 0   poc                   int64
 1   latitude              float64
 2   longitude             float64
 3   datum                 object
 4   parameter             object
 5   sample_duration_code  object
 6   sample_duration       object
 7   pollutant_standard    object
 8   date_local            object
 9   units_of_measure      object
 10  event_type            object
 11  observation_count     int64
 12  observation_percent   float64
 13  validity_indicator    object
 14  arithmetic_mean       float64
 15  first_max_value       float64
 16  first_max_hour        int64
 17  aqi                   float64
 18  method_code           float64
 19  method                object
 20  local_site_name       object
 21  site_address          object
 22  state                 object
 23  county                object
 24  city                  object
dtypes: float64(7), int64(3), object(15)
memory usage: 758.1+ MB

None

Arizona Air Pollutants Head
==================================================
==================================================

,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city
0,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-01,Parts per million,No Events,24,100.0,Y,4.237500,10.2,1,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix
1,1,33.49462,-112.13098,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,1993-01-01,Parts per million,No Events,19,79.0,Y,4.210526,8.6,5,92.0,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix
2,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-02,Parts per million,No Events,24,100.0,Y,2.495833,4.9,8,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix
3,1,33.49462,-112.13098,WGS84,Carbon monoxide,Z,8-HR RUN AVG END HOUR,CO 8-hour 1971,1993-01-02,Parts per million,No Events,24,100.0,Y,2.441667,3.2,8,36.0,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix
4,1,33.49462,-112.13098,WGS84,Carbon monoxide,1,1 HOUR,CO 1-hour 1971,1993-01-03,Parts per million,No Events,24,100.0,Y,1.112500,3.1,0,NaN,11.0,INSTRUMENTAL - NONDISPERSIVE INFRARED,WEST INDIAN SCHOOL RD,"3315 W INDIAN SCHOOL RD, PHOENIX",Arizona,Maricopa,Phoenix

Arizona Air Pollutants Tail
==================================================
==================================================

,poc,latitude,longitude,datum,parameter,sample_duration_code,sample_duration,pollutant_standard,date_local,units_of_measure,event_type,observation_count,observation_percent,validity_indicator,arithmetic_mean,first_max_value,first_max_hour,aqi,method_code,method,local_site_name,site_address,state,county,city
3974372,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-17,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.008,1.008,0,NaN,808.0,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city
3974373,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-20,Micrograms/cubic meter (LC),No Events,1,100.0,Y,1.573,1.573,0,NaN,808.0,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city
3974374,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-23,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.518,0.518,0,NaN,808.0,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city
3974375,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-26,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.544,0.544,0,NaN,808.0,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city
3974376,1,34.058475,-109.441259,WGS84,PM10 - LC,7,24 HOUR,NaN,2023-12-29,Micrograms/cubic meter (LC),No Events,1,100.0,Y,0.796,0.796,0,NaN,808.0,IMPROVE Module D with Cyclone Inlet-Teflon Fil...,Mount Baldy,Mount Baldy,Arizona,Apache,Not in a city